// @flow
export const images = {
  'alumni-hall': require('./optimized/alumni-hall.jpg'),
  'boe': require('./optimized/boe.jpg'),
  'bookstore': require('./optimized/bookstore.jpg'),
  'buntrock': require('./optimized/buntrock.jpg'),
  'cage': require('./optimized/cage.jpg'),
  'center-for-arts-and-dance': require('./optimized/center-for-arts-and-dance.jpg'),
  'christiansen': require('./optimized/christiansen.jpg'),
  'convenience': require('./optimized/convenience.jpg'),
  'disco': require('./optimized/disco.jpg'),
  'hall-of-music': require('./optimized/hall-of-music.jpg'),
  'halvorson': require('./optimized/halvorson.jpg'),
  'old-main': require('./optimized/old-main.jpg'),
  'pause-kitchen': require('./optimized/pause-kitchen.jpg'),
  'print': require('./optimized/print.jpg'),
  'post-office': require('./optimized/post-office.jpg'),
  'regents-hall': require('./optimized/regents-hall.jpg'),
  'regents-math': require('./optimized/regents-math.jpg'),
  'rolvaag-library': require('./optimized/rolvaag-library.jpg'),
  'skifter-studioa': require('./optimized/skifter-studioa.jpg'),
  'skoglund': require('./optimized/skoglund.jpg'),
  'stav': require('./optimized/stav.jpg'),
  'theater': require('./optimized/theater.jpg'),
  'tom-porter': require('./optimized/tom-porter.jpg'),
  'tomson': require('./optimized/tomson.jpg'),
  'wellness': require('./optimized/wellness.jpg'),
}
