---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
    - "**/__tests__/"
    config:
      languages:
      - ruby
      - javascript
      - python
  eslint:
    enabled: true
    channel: "eslint-4"
  fixme:
    enabled: true
  radon:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-0-51"

ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"

exclude_patterns:
- node_modules/
- flow-typed/
