coverage:
  precision: 2
  round: down
  range: 8...100

  status:
    project: true
    patch: false
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: diff
  behavior: default
  require_changes: true

github_checks:
  annotations: false
