---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

plugins:
  - '@typescript-eslint'
  - babel
  - jsx-expressions
  - react
  - react-native
  - react-hooks

extends:
  - eslint:recommended
  - plugin:react/recommended
  - 'plugin:@typescript-eslint/recommended'
  - prettier

settings:
  react:
    version: '16.6'

env:
  es6: true
  react-native/react-native: true

rules:
  array-callback-return: error
  camelcase: warn
  consistent-this: [error, self]
  curly: [warn, multi-line]
  default-case: error
  guard-for-in: error
  eqeqeq: [error, smart]
  linebreak-style: [error, unix]
  new-cap: off
  no-await-in-loop: warn
  no-case-declarations: error
  no-console: off
  no-div-regex: error
  no-extra-label: error
  no-implicit-coercion:
    - error
    - boolean: true
      number: true
      string: true
  no-implicit-globals: error
  no-multi-assign: error
  no-new-symbol: error
  no-restricted-syntax: [error, WithStatement]
  no-return-await: error
  no-throw-literal: error
  no-undef-init: off
  no-underscore-dangle: off
  no-unmodified-loop-condition: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: 'after-used'
      argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  no-useless-constructor: error
  no-var: error
  prefer-const: off
  prefer-promise-reject-errors: error
  prefer-spread: error
  quotes: [warn, single, avoid-escape]
  require-await: warn
  semi: off
  no-misleading-character-class: warn
  require-atomic-updates: error
  no-async-promise-executor: error
  require-unicode-regexp: error

  # react rules – https://github.com/yannickcr/eslint-plugin-react
  react/display-name: off
  react/jsx-curly-brace-presence: [warn, never]
  react/jsx-key: warn
  react/jsx-no-bind:
    - warn
    - ignoreRefs: true
      allowArrowFunctions: true
  react/jsx-sort-props:
    - warn
    - reservedFirst: true
      ignoreCase: false
  react/no-access-state-in-setstate: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-multi-comp: off # prevent multiple component definition per file
  react/no-redundant-should-component-update: warn
  react/no-typos: error
  react/prop-types: off
  react/self-closing-comp: warn # prevent extra closing tags for components without children
  react/sort-comp:
    - warn
    - order:
        - static-variables
        - static-methods
        - type-annotations
        - lifecycle
        - everything-else
        - render
  react/sort-prop-types: warn
  react/wrap-multilines: off
  react/jsx-boolean-value: [error, always]

  # react-native rules
  react-native/no-unused-styles: warn
  react-native/no-inline-styles: warn
  react-native/no-color-literals: warn

  # react hooks rules
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

  # TODO(rye): Follow-up: DENY these
  '@typescript-eslint/explicit-module-boundary-types': warn
  '@typescript-eslint/no-empty-function': warn

  # eslint-plugin-jsx-expressions – https://github.com/hpersson/eslint-plugin-jsx-expressions/
  jsx-expressions/strict-logical-expressions: warn
