parser: babel-eslint
extends: eslint:recommended
installedESLint: true

env:
  es6: true
  node: true

parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

plugins: [babel, react, flowtype]

globals:
  fetch: true
  FormData: true
  fetchJson: true
  rawFetch: true
  __DEV__: true

rules:
  array-callback-return: error
  arrow-parens: [warn, as-needed]
  arrow-spacing: [warn, {before: true, after: true}]
  brace-style: [warn, 1tbs]
  camelcase: warn
  comma-dangle: [warn, always-multiline]
  comma-spacing: [warn, {before: false, after: true}]
  comma-style: [warn, last]
  consistent-this: [error, self]
  curly: [warn, multi-line]
  default-case: error
  eol-last: [warn, always]
  guard-for-in: error
  indent: [warn, 2, {SwitchCase: 1, MemberExpression: 1}]
  key-spacing: [warn, {beforeColon: false, afterColon: true}]
  keyword-spacing: warn
  linebreak-style: [error, unix]
  new-cap: 'off'
  no-await-in-loop: warn
  no-case-declarations: error
  no-confusing-arrow: 'off'
  no-console: 'off'
  no-div-regex: error
  no-eq-null: warn
  no-extra-label: error
  no-implicit-coercion: [error, {boolean: true, number: true, string: true}]
  no-implicit-globals: error
  no-multi-assign: error
  no-new-symbol: error
  no-restricted-syntax: [error, WithStatement]
  no-return-await: error
  no-trailing-spaces: warn
  no-throw-literal: error
  no-undef-init: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unused-vars: [warn, {args: 'after-used', argsIgnorePattern: '^_$'}]
  no-useless-constructor: error
  no-var: error
  no-whitespace-before-property: warn
  one-var-declaration-per-line: error
  prefer-promise-reject-errors: error
  prefer-spread: error
  quotes: [warn, single, avoid-escape]
  require-await: warn
  semi: [error, never]
  template-tag-spacing: [warn, never]
  wrap-iife: error

  # react rules – https://github.com/yannickcr/eslint-plugin-react
  jsx-quotes: [warn, prefer-single]
  react/display-name: 'off'
  react/jsx-curly-spacing: [warn, never]
  react/jsx-indent-props: [warn, 2]
  react/jsx-no-duplicate-props: warn
  react/jsx-no-undef: error
  react/jsx-space-before-closing: warn
  react/jsx-uses-react: warn
  react/jsx-uses-vars: warn
  react/no-deprecated: warn
  react/no-did-mount-set-state: warn
  react/no-did-update-set-state: warn
  react/no-direct-mutation-state: warn
  react/no-multi-comp: 'off'  # prevent multiple component definition per file
  react/no-unknown-property: warn
  react/prefer-stateless-function: warn
  react/prop-types: warn  # prevent missing proptypes in a react component definition
  react/react-in-jsx-scope: warn
  react/self-closing-comp: warn  # prevent extra closing tags for components without children
  react/sort-comp: warn
  react/sort-prop-types: warn
  react/wrap-multilines: 'off'

  # flow rules
  flowtype/define-flow-type: warn
  flowtype/space-after-type-colon: [warn, always]
  flowtype/space-before-type-colon: [warn, never]
  flowtype/use-flow-type: error
  flowtype/valid-syntax: error
