AllCops:
  Exclude:
    - 'node_modules/**/*'

Layout/Tab:
  IndentationWidth: 2

Naming/PredicateName:
  Exclude:
    - 'fastlane/actions/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
