AllCops:
  Exclude:
    - 'node_modules/**/*'

Layout/IndentationWidth:
  Width: 1 # 1 tab...

Layout/Tab:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - 'fastlane/actions/*.rb'

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
