shallow_clone: true
clone_folder: c:\projects\all-about-olaf

# From http://stackoverflow.com/a/31882307/2347774
# Hopefully prevent appveyor from building twice for PRs
branches:
  only:
    - master

# the basic outline for this install process is from
# github.com/googlesamples/android-ndk/blob/master/appveyor.yml
init:
  # prepare android-sdk
  - cd \
  - appveyor DownloadFile "http://dl.google.com/android/android-sdk_r24.4.1-windows.zip"
  - 7z x "android-sdk_r24.4.1-windows.zip" > nul
  - cd c:\projects\all-about-olaf

install:
  # install android-sdk
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-23,platform-tools,tools,build-tools-23.0.1,extra-google-m2repository,extra-android-m2repository,extra-android-support
  # install node and npm packages
  - ps: Install-Product node $env:nodejs_version
  # switch to yarn for faster install times
  - yarn

environment:
  nodejs_version: '7'
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  ANDROID_HOME: C:\android-sdk-windows
  matrix:
    - TEST_TYPE: android

# Post-install test scripts.
test_script:
  - node --version
  - yarn -V

build_script: cd android && gradlew assembleRelease --info --console=plain --parallel

notifications:
  - provider: Slack
    incoming_webhook:
      secure: FAKVymf5kPEMsOf2Brk5VWIeylmsG6oCXBBURcN3S2RTSKGvLV/qEiN1m2HWU+OxGlnMZcBR7UjB2hsOw6S/Ri81KDzgpuTWcYH9FOobXWU=
