packages:
  - ./
  - modules/*

allowBuilds:
  '@sentry/cli': false
  detox: false
  dtrace-provider: false
  react-native-inappbrowser-reborn: false
  unrs-resolver: false

autoInstallPeers: false

blockExoticSubdeps: true

catalog:
  '@callstack/react-theme-provider': 3.0.9
  '@expo/react-native-action-sheet': 4.1.1
  '@expo/ui': 0.2.0-beta.9
  '@frogpond/titlecase': 2.0.4
  '@hawkrives/react-native-alternate-icons': 0.6.2
  '@react-native-async-storage/async-storage': 2.2.0
  '@react-native-clipboard/clipboard': 1.16.3
  '@react-native-community/datetimepicker': 8.6.0
  '@react-native-community/netinfo': 11.4.1
  '@react-native-picker/picker': 2.11.4
  '@react-native-vector-icons/entypo': 12.4.0
  '@react-native-vector-icons/ionicons': 12.3.0
  '@react-native-vector-icons/material-design-icons': 12.4.0
  '@react-navigation/bottom-tabs': 6.6.1
  '@react-navigation/native': 6.1.18
  '@react-navigation/native-stack': 6.11.0
  '@react-navigation/stack': 6.4.1
  '@reduxjs/toolkit': 2.11.2
  '@sentry/react-native': 7.9.0
  '@tanstack/query-async-storage-persister': 5.90.21
  '@tanstack/react-query': 5.90.19
  '@tanstack/react-query-persist-client': 5.90.21
  base-64: 1.0.0
  buffer: 6.0.3
  css-select: ^6.0.0
  delay: 7.0.0
  domhandler: ^5.0.3
  domutils: ^3.2.2
  events: 3.3.0
  expo: 54.0.31
  expo-application: 7.0.8
  expo-asset: 12.0.12
  expo-calendar: 15.0.8
  expo-constants: 18.0.13
  expo-device: 8.0.10
  expo-font: 14.0.10
  expo-secure-store: 15.0.8
  expo-status-bar: 3.0.9
  expo-system-ui: 6.0.9
  expo-updates: 29.0.16
  expo-web-browser: 15.0.10
  html-entities: ^2.6.0
  htmlparser2: ^10.0.0
  keyword-search: 0.1.2
  ky: 1.14.2
  lodash: 4.17.21
  moment: 2.30.1
  moment-timezone: 0.5.45
  p-props: 6.1.0
  react: 19.1.0
  react-markdown: 2.5.1
  react-native: 0.81.5
  react-native-button: 3.1.0
  react-native-calendar-events: 2.2.0
  react-native-gesture-handler: 2.28.0
  react-native-inappbrowser-reborn: 3.7.0
  react-native-ios-context-menu: 1.15.3
  react-native-network-logger: 2.0.1
  react-native-paper: 5.14.5
  react-native-popover-view: 5.1.8
  react-native-reanimated: 4.1.1
  react-native-safe-area-context: 5.6.2
  react-native-screens: 4.16.0
  react-native-search-bar: 3.5.1
  react-native-tableview-simple: 4.4.1
  react-native-typography: 1.4.1
  react-native-webview: 13.15.0
  react-native-worklets: 0.5.1
  react-redux: 9.2.0
  redux-persist: 6.0.0
  stream: 0.0.3
  timers: 0.1.1
  tinycolor2: 1.6.0
  url: 0.11.4
  wordwrap: 1.0.0

catalogMode: strict

cleanupUnusedCatalogs: true

enableGlobalVirtualStore: true

hoistPattern: []

ignoreWorkspaceRootCheck: true

lockfileIncludeTarballUrl: false

optimisticRepeatInstall: true

overrides:
  react-native>@react-native/community-cli-plugin: '-'

packageExtensions:
  '@sentry/react-native@7.9.0':
    peerDependencies:
      '@expo/config-plugins': '*'

shellEmulator: true

strictDepBuilds: true

strictPeerDependencies: true
