// flow-typed signature: df6cbc2a4a97b6b132a0e5aa8c37ebe9
// flow-typed version: <<STUB>>/@sentry/cli_v1.48.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/cli' {
  declare module.exports: any;
}
