// flow-typed signature: b6d40412729329b62b4b8d523269dda8
// flow-typed version: <<STUB>>/@sentry/react-native_v1.6.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/react-native' {
  declare module.exports: any;
}
