// flow-typed signature: d54d84d21381aece5867e65faa388883
// flow-typed version: <<STUB>>/@sentry/react-native_v1.0.9/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/react-native' {
  declare module.exports: any;
}
