// flow-typed signature: da3be46918004c777f5cae071f4d64d7
// flow-typed version: <<STUB>>/ajv_v6.5.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv' {
  declare module.exports: any;
}
