// flow-typed signature: 3805a8eb9c47bb120626241ba0851ffc
// flow-typed version: <<STUB>>/ajv_v6.10.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv' {
  declare module.exports: any;
}
