// flow-typed signature: 54fa2e2e5d598eb05a62f8ba9f7f6209
// flow-typed version: <<STUB>>/ajv_v6.1.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv' {
  declare module.exports: any;
}
