// flow-typed signature: a35bcce46deb4b728da4162385ae5982
// flow-typed version: <<STUB>>/babel-plugin-transform-remove-console_v6.9.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-remove-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-remove-console' {
  declare module.exports: any;
}
