// flow-typed signature: f9ad18c1fe2e1ac3c67b5d478c17941b
// flow-typed version: <<STUB>>/babel-eslint_v8.2.1/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
