// flow-typed signature: 01935607d6895492a2f5f54072671b7d
// flow-typed version: <<STUB>>/babel-plugin-transform-remove-console_v6.9.4/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-remove-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-remove-console' {
  declare module.exports: any;
}
