// flow-typed signature: 5ccab3f0bb51e66398707f22c9954f9e
// flow-typed version: <<STUB>>/babel-preset-react-native_v1.9.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native' {
  declare module.exports: any;
}
