// flow-typed signature: 1cb0d48c38d0f6dbba6e3dd8fc64c913
// flow-typed version: <<STUB>>/babel-jest_v22.1.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-jest' {
  declare module.exports: any;
}
