// flow-typed signature: bf02711d861c6c87dd56155e77b9f8a8
// flow-typed version: <<STUB>>/babel-plugin-flow-react-proptypes_v0.19.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-flow-react-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-flow-react-proptypes' {
  declare module.exports: any;
}
