// flow-typed signature: e7410b01dd1230b3dbacb243c4218597
// flow-typed version: <<STUB>>/babel-plugin-flow-react-proptypes_v0.17.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-flow-react-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-flow-react-proptypes' {
  declare module.exports: any;
}
