// flow-typed signature: 8f859d7932a4250bd52903336f294c5c
// flow-typed version: <<STUB>>/babel-core_v6.26.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}
