// flow-typed signature: c10e0c8048bf76d822c0e402795ecad8
// flow-typed version: <<STUB>>/babel-preset-react-native_v4.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native' {
  declare module.exports: any;
}
