// flow-typed signature: ccc7a48cad71bfb8f71031e99a3c3e2e
// flow-typed version: <<STUB>>/babel-jest_v22.2.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-jest' {
  declare module.exports: any;
}
