// flow-typed signature: 2e42ddcf869860d1cfa6d4a868ef9534
// flow-typed version: <<STUB>>/babel-eslint_v10.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
