// flow-typed signature: d726b39d44c7bd0b503befb6c6d89070
// flow-typed version: <<STUB>>/babel-core_v6.26.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}
