// flow-typed signature: ecf9b1ed42901067005a867d130c3fc0
// flow-typed version: <<STUB>>/babel-jest_v17.0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-jest' {
  declare module.exports: any;
}
