// flow-typed signature: 33a3692df0d07227b8fc58c9d6658037
// flow-typed version: <<STUB>>/babel-core_v6.26.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}
