// flow-typed signature: 1397fc94a7adc815fa3397f244cc9bae
// flow-typed version: <<STUB>>/babel-preset-react-native_v4.0.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native' {
  declare module.exports: any;
}
