// flow-typed signature: 3385b66090af2997c70941512ed6c06f
// flow-typed version: <<STUB>>/buffer_v5.4.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}
