// flow-typed signature: f5ef880ace39262efd1f0676dde5f3dc
// flow-typed version: <<STUB>>/buffer_v5.2.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}
