// flow-typed signature: bd2db873346699fe2315aa59938cf991
// flow-typed version: <<STUB>>/buffer_v5.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}
