// flow-typed signature: 74438997241b9ab2e2677dc13014bd00
// flow-typed version: <<STUB>>/bugsnag-react-native_v2.5.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-react-native' {
  declare module.exports: any;
}
