// flow-typed signature: 59adf8aeeaf233fe16df5b1625941732
// flow-typed version: <<STUB>>/bugsnag-sourcemaps_v1.0.1/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-sourcemaps' {
  declare module.exports: any;
}
