// flow-typed signature: e6b18a6cd24eac6812ab02669df67d3c
// flow-typed version: <<STUB>>/css-select_v1.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-select/lib/attributes' {
  declare module.exports: any;
}

declare module 'css-select/lib/compile' {
  declare module.exports: any;
}

declare module 'css-select/lib/general' {
  declare module.exports: any;
}

declare module 'css-select/lib/pseudos' {
  declare module.exports: any;
}

declare module 'css-select/lib/sort' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-select/index' {
  declare module.exports: $Exports<'css-select'>;
}
declare module 'css-select/index.js' {
  declare module.exports: $Exports<'css-select'>;
}
declare module 'css-select/lib/attributes.js' {
  declare module.exports: $Exports<'css-select/lib/attributes'>;
}
declare module 'css-select/lib/compile.js' {
  declare module.exports: $Exports<'css-select/lib/compile'>;
}
declare module 'css-select/lib/general.js' {
  declare module.exports: $Exports<'css-select/lib/general'>;
}
declare module 'css-select/lib/pseudos.js' {
  declare module.exports: $Exports<'css-select/lib/pseudos'>;
}
declare module 'css-select/lib/sort.js' {
  declare module.exports: $Exports<'css-select/lib/sort'>;
}
