// flow-typed signature: cc95650448bf00f9b492a6d7e25c5e67
// flow-typed version: <<STUB>>/danger-plugin-yarn_v1.3.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-yarn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-yarn' {
  declare module.exports: any;
}
