// flow-typed signature: c4a3151ee6b5e58fab5602ea8cfdbe97
// flow-typed version: <<STUB>>/danger-plugin-yarn_v1.2.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-yarn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-yarn' {
  declare module.exports: any;
}
