// flow-typed signature: 8fc6647aeb809ec2eb50f8bf113f63a2
// flow-typed version: <<STUB>>/danger-plugin-yarn_v1.3.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-yarn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-yarn' {
  declare module.exports: any;
}
