// flow-typed signature: f6c398f25c2f579dc403f4001c785b25
// flow-typed version: <<STUB>>/delay_v1.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'delay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'delay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'delay/index' {
  declare module.exports: $Exports<'delay'>;
}
declare module 'delay/index.js' {
  declare module.exports: $Exports<'delay'>;
}
