// flow-typed signature: 850ba5ac79a349fb8fcb9751abbfb2c0
// flow-typed version: <<STUB>>/directory-tree_v2.0.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'directory-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'directory-tree' {
  declare module.exports: any;
}
