// flow-typed signature: 082becb324dceb7eec399eb7d8ee2fbf
// flow-typed version: <<STUB>>/directory-tree_v2.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'directory-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'directory-tree' {
  declare module.exports: any;
}
