// flow-typed signature: e5137c39738e40b88ff63213ae96c226
// flow-typed version: <<STUB>>/eslint-plugin-react-hooks_v2.2.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-hooks' {
  declare module.exports: any;
}
