// flow-typed signature: b9592a200b54f8194acb048b2b3f7d10
// flow-typed version: <<STUB>>/eslint-config-prettier_v6.5.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
