// flow-typed signature: 909ae7839899b52710276fd509db9757
// flow-typed version: <<STUB>>/eslint-plugin-react-hooks_v4.0.8/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-hooks' {
  declare module.exports: any;
}
