// flow-typed signature: d57de0a5d2256821081f3c54d980f564
// flow-typed version: <<STUB>>/eslint-plugin-babel_v5.3.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}
