// flow-typed signature: a907fa6e74e07a5607ec3f09816c0ee0
// flow-typed version: <<STUB>>/eslint-plugin-react_v7.12.4/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
