// flow-typed signature: 44641d620cc8155ac08bad02be696bc1
// flow-typed version: <<STUB>>/eslint_v3.12.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
