// flow-typed signature: 24967fccd122ae067a400394635407cb
// flow-typed version: <<STUB>>/eslint_v5.15.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
