// flow-typed signature: f32bfdf090fd6f5f79cf4e5e80670be2
// flow-typed version: <<STUB>>/eslint-config-prettier_v2.9.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
