// flow-typed signature: a4651ba0ea2924d962e22a295263a253
// flow-typed version: <<STUB>>/eslint-plugin-react_v7.14.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
