// flow-typed signature: 09d932d23eaf0aef0032ba7688508c6d
// flow-typed version: <<STUB>>/eslint-plugin-babel_v4.1.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}
