// flow-typed signature: 79ed554caddfabb02d8234e0697ada90
// flow-typed version: <<STUB>>/eslint_v6.6.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
