// flow-typed signature: fc747458d5e69006aad7cddecb0dd1c1
// flow-typed version: <<STUB>>/eslint-plugin-react_v6.8.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
