// flow-typed signature: 2fc32f057996d97d768fc5c6494ae9f5
// flow-typed version: <<STUB>>/eslint-plugin-react-native_v3.8.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-native' {
  declare module.exports: any;
}
