// flow-typed signature: e2623a360cb2f4c1a57c712f5dccd1f0
// flow-typed version: <<STUB>>/eslint-plugin-flowtype_v4.3.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype' {
  declare module.exports: any;
}
