// flow-typed signature: e7f839f2f9c5670ca76326298ddf97c3
// flow-typed version: <<STUB>>/eslint-plugin-react-native_v3.3.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-native' {
  declare module.exports: any;
}
