// flow-typed signature: 6e4df712dc7b781eb209b0a48dacc0d4
// flow-typed version: <<STUB>>/eslint-plugin-flowtype_v2.46.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype' {
  declare module.exports: any;
}
