// flow-typed signature: ce7a9f79f3902d8bc87a6c1772fb46dd
// flow-typed version: <<STUB>>/eslint-plugin-babel_v5.3.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}
