// flow-typed signature: 9fdad63f0f59eb21e817673e073dca49
// flow-typed version: <<STUB>>/eslint-plugin-flowtype_v3.4.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype' {
  declare module.exports: any;
}
