// flow-typed signature: 3bfc05dcf61c783ff0173faa0c7f84ad
// flow-typed version: <<STUB>>/events_v3.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'events' {
  declare module.exports: any;
}
