// flow-typed signature: 5b2e46e927f89f4eb22ba4c0d7c15b2f
// flow-typed version: <<STUB>>/events_v3.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'events' {
  declare module.exports: any;
}
