// flow-typed signature: 86bde9c64463d3ecb32ea45e1a0570f7
// flow-typed version: <<STUB>>/frisbee_v1.1.6/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'frisbee'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'frisbee' {
  declare module.exports: any;
}
