// flow-typed signature: 064fa4361244764a143997bf574ca911
// flow-typed version: <<STUB>>/frisbee_v1.1.5/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'frisbee'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'frisbee' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'frisbee/examples/basic/app' {
  declare module.exports: any;
}

declare module 'frisbee/lib/frisbee' {
  declare module.exports: any;
}

// Filename aliases
declare module 'frisbee/examples/basic/app.js' {
  declare module.exports: $Exports<'frisbee/examples/basic/app'>;
}
declare module 'frisbee/lib/frisbee.js' {
  declare module.exports: $Exports<'frisbee/lib/frisbee'>;
}
