// flow-typed signature: f2bda34a7450303cf1940af57731f577
// flow-typed version: <<STUB>>/glamorous-native_v2.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamorous-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamorous-native' {
  declare module.exports: any;
}
