// flow-typed signature: eab2205e09eb7c980965cc809688771e
// flow-typed version: <<STUB>>/glamorous-native_v1.4.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamorous-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamorous-native' {
  declare module.exports: any;
}
