// flow-typed signature: 38d2415321bf69f55374bf39346616a0
// flow-typed version: <<STUB>>/html-entities_v1.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-entities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-entities' {
  declare module.exports: any;
}
