// flow-typed signature: d7fb6d1edcf85a72a9738e9ceaa02c5f
// flow-typed version: <<STUB>>/html-entities_v1.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-entities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-entities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-entities/lib/html4-entities' {
  declare module.exports: any;
}

declare module 'html-entities/lib/html5-entities' {
  declare module.exports: any;
}

declare module 'html-entities/lib/xml-entities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-entities/index' {
  declare module.exports: $Exports<'html-entities'>;
}
declare module 'html-entities/index.js' {
  declare module.exports: $Exports<'html-entities'>;
}
declare module 'html-entities/lib/html4-entities.js' {
  declare module.exports: $Exports<'html-entities/lib/html4-entities'>;
}
declare module 'html-entities/lib/html5-entities.js' {
  declare module.exports: $Exports<'html-entities/lib/html5-entities'>;
}
declare module 'html-entities/lib/xml-entities.js' {
  declare module.exports: $Exports<'html-entities/lib/xml-entities'>;
}
