// flow-typed signature: 2c91316993493cf825e2f62686c26247
// flow-typed version: <<STUB>>/htmlparser2_v3.9.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlparser2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlparser2' {
  declare module.exports: any;
}
