// flow-typed signature: 0fd8ca00af00de59b18ad3bfea2a6365
// flow-typed version: <<STUB>>/jest-react-native_v17.0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-react-native' {
  declare module.exports: any;
}
