// flow-typed signature: 084189137c755196f819935cd527b319
// flow-typed version: <<STUB>>/jest-junit_v3.5.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-junit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-junit' {
  declare module.exports: any;
}
