// flow-typed signature: e6b1ee6d067b7923b5137a12ddca4140
// flow-typed version: <<STUB>>/jetifier_v1.6.4/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jetifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jetifier' {
  declare module.exports: any;
}
