// flow-typed signature: fb38d1f4956dab7f253ab1eb2966a589
// flow-typed version: <<STUB>>/jetifier_v1.6.6/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jetifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jetifier' {
  declare module.exports: any;
}
