// flow-typed signature: 492c4ddbf0356bc65846f5819dd6b2d9
// flow-typed version: <<STUB>>/js-yaml_v3.10.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}
