// flow-typed signature: 0cd944d361ff13c1dcf64d8a722cee16
// flow-typed version: <<STUB>>/jsc-android_v224109.x.x/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsc-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsc-android' {
  declare module.exports: any;
}
