// flow-typed signature: 327e065221e2680b62c943988b9c170a
// flow-typed version: <<STUB>>/jsc-android_v241213.1.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsc-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsc-android' {
  declare module.exports: any;
}
