// flow-typed signature: cfef7a4bee5e2f74c88e74725faf3448
// flow-typed version: <<STUB>>/jsc-android_v236355.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsc-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsc-android' {
  declare module.exports: any;
}
