// flow-typed signature: 677710f6823e9bbf4c18d3e9e6e16061
// flow-typed version: <<STUB>>/keyword-search_v0.1.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keyword-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keyword-search' {
  declare module.exports: any;
}
