// flow-typed signature: d994e173f9fbea33ef89d6ae146d8e9c
// flow-typed version: <<STUB>>/metro-react-native-babel-preset_v0.53.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metro-react-native-babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metro-react-native-babel-preset' {
  declare module.exports: any;
}
