// flow-typed signature: 8a4a3c369df94f02e37a941a5bd08c7d
// flow-typed version: <<STUB>>/metro-react-native-babel-preset_v0.61.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metro-react-native-babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metro-react-native-babel-preset' {
  declare module.exports: any;
}
