// flow-typed signature: 6de07ed38b551b09d15ebdd8079428a9
// flow-typed version: <<STUB>>/metro-react-native-babel-preset_v0.57.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metro-react-native-babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metro-react-native-babel-preset' {
  declare module.exports: any;
}
