// flow-typed signature: e4d75cbede4aeed3ad3c5d6c20b3e4ab
// flow-typed version: <<STUB>>/mkdirp_v1.0.4/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mkdirp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mkdirp' {
  declare module.exports: {
    sync(path: string, options?: Options): void,
  }
}
