// flow-typed signature: e7dce66c88bc6a4a5c395eaee7bca5c7
// flow-typed version: <<STUB>>/moment-timezone_v0.5.10/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-timezone' {
  declare module.exports: any;
}
