// flow-typed signature: 0a9956fb62e9738cbdde9a601430eb3f
// flow-typed version: <<STUB>>/moment-timezone_v0.5.11/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-timezone' {
  declare module.exports: any;
}
