// flow-typed signature: 2aa399a082a6decc2d9df4187a684c0a
// flow-typed version: <<STUB>>/moment-timezone_v0.5.9/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

import type moment from 'moment'

declare module 'moment-timezone' {
  declare module.exports: moment
}
