// flow-typed signature: 22ee071b9f074eed8b04f11ffc478b5b
// flow-typed version: <<STUB>>/p-props_v2.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-props' {
  declare module.exports: any;
}
