// flow-typed signature: 405a8c1f7ac6b3f6d98ba13ffbc9d754
// flow-typed version: <<STUB>>/p-props_v4.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-props' {
  declare module.exports: any;
}
