// flow-typed signature: b7e2c2457061e516965a6555f272f2c7
// flow-typed version: <<STUB>>/p-props_v1.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-props' {
  declare module.exports: any;
}
