// flow-typed signature: 8a799d719d197534d36c8c045a2d6052
// flow-typed version: <<STUB>>/p-retry_v1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-retry' {
  declare module.exports: any;
}
