// flow-typed signature: a00a5b6c26c0bb7f590d078c0ac38658
// flow-typed version: <<STUB>>/p-retry_v4.2.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-retry' {
  declare module.exports: any;
}
