// flow-typed signature: 8fb534c689c54fbb19c032eae496761b
// flow-typed version: <<STUB>>/pify_v5.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}
