// flow-typed signature: 95851b3d94d2b51bf1294edfe775bc24
// flow-typed version: <<STUB>>/pretty-quick_v2.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}
