// flow-typed signature: 519df331f5b33d9ee1b77d0f924edc2e
// flow-typed version: <<STUB>>/pretty-quick_v1.6.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}
