// flow-typed signature: 1952a9ed651f9a3e36f816b0cd8ff7c2
// flow-typed version: <<STUB>>/pretty-quick_v1.10.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}
