// flow-typed signature: 95d2b94ef0d1bfc2931fac30d26c35ea
// flow-typed version: <<STUB>>/prettier_v1.10.2/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
