// flow-typed signature: d27c0fc79ba4f5aa2bb947e503f5b5e3
// flow-typed version: <<STUB>>/prettier_v2.0.5/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
