// flow-typed signature: eca5a29f2edcc28af6afb46740eefbc4
// flow-typed version: <<STUB>>/querystring_v0.2.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystring' {
  declare module.exports: any;
}
