// flow-typed signature: 998df1327a35d90bd935c1ed07c9e3a5
// flow-typed version: <<STUB>>/querystring_v0.2.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystring' {
  declare module.exports: any;
}
