// flow-typed signature: a56ba7502bfe975dd6c3f9392f7bc688
// flow-typed version: <<STUB>>/react-native-vector-icons_v4.6.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-vector-icons' {
  declare module.exports: any;
}
