// flow-typed signature: 372741045c00e3262cd72c0fb505ca9d
// flow-typed version: <<STUB>>/react-native-popover-view_v1.0.17/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popover-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popover-view' {
  declare module.exports: any;
}
