// flow-typed signature: 180b19ac34dda58974d027dedce6024b
// flow-typed version: <<STUB>>/react-navigation-material-bottom-tabs_v1.1.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-material-bottom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-material-bottom-tabs' {
  declare module.exports: any;
}
