// flow-typed signature: ab86b30867ed98ef143c44b3b4983e5c
// flow-typed version: <<STUB>>/react-native-onesignal_v3.2.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-onesignal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-onesignal' {
  declare module.exports: any;
}
