// flow-typed signature: ce4ef32863991b3b2e0e3dcdf2a089d1
// flow-typed version: <<STUB>>/react-native-cookies_v2.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cookies' {
  declare module.exports: any;
}
