// flow-typed signature: b0dcfd2b714d2e5273a34d974efe3a0a
// flow-typed version: <<STUB>>/react-native-typography_v1.4.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-typography' {
  declare module.exports: any;
}
