// flow-typed signature: 6092fc4eb5f88354104d9f6156229e7c
// flow-typed version: <<STUB>>/react-native-searchbar-controlled_v1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-searchbar-controlled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-searchbar-controlled' {
  declare module.exports: any;
}
