// flow-typed signature: 2e4f9ce128190ddc77344f482b9e9bcf
// flow-typed version: <<STUB>>/react-native-webview_v7.4.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webview' {
  declare module.exports: any;
}
