// flow-typed signature: 322663b29fff985a1988d5995a1c4f69
// flow-typed version: <<STUB>>/react-native-search-bar_v3.4.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-search-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-search-bar' {
  declare module.exports: any;
}
