// flow-typed signature: 376e4ce61b093f275d4572bb1f7352e8
// flow-typed version: <<STUB>>/react-native-parallax-view_v2.0.6/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-parallax-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-parallax-view' {
  declare module.exports: any;
}
