// flow-typed signature: 9de2f57b36ec11caf6f40062cd9f68cd
// flow-typed version: <<STUB>>/react-native-sortable-list_vgithub:hawkrives/react-native-sortable-list#a46c78161e0a1a8d3a45f2fef69d98af3e911b6d/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sortable-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sortable-list' {
  declare module.exports: any;
}
