// flow-typed signature: 319be068e0ea6fe66f4ae64c2b36d613
// flow-typed version: <<STUB>>/react-test-renderer_v15.4.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}
