// flow-typed signature: 9606d51c0089f2b196e6922c6e0efc6f
// flow-typed version: <<STUB>>/react-navigation_v1.0.0-beta.19/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation' {
  declare module.exports: any;
}
