// flow-typed signature: 75eb46d36a7c4d4137ec3db52fb074df
// flow-typed version: <<STUB>>/react-native-vector-icons_v3.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-vector-icons/Entypo' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Foundation' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Octicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Zocial' {
  declare module.exports: any;
}
