// flow-typed signature: 82b4c557df28387c655bd02069f840b4
// flow-typed version: <<STUB>>/react-native-gesture-handler_v1.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gesture-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gesture-handler' {
  declare module.exports: any;
}
