// flow-typed signature: 75c2fc59cc6f2c1bcb9c21a96e5a7bb4
// flow-typed version: <<STUB>>/react-native-maps_v0.19.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}
