// flow-typed signature: a41d42ff30bc94bbca782aed9a0b2618
// flow-typed version: <<STUB>>/react-native-button_v1.7.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-button' {
  declare module.exports: any;
}
