// flow-typed signature: c739631aafa163b79c6f92c4b616b3c0
// flow-typed version: <<STUB>>/react-native-search-bar_v3.5.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-search-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-search-bar' {
  declare module.exports: any;
}
