// flow-typed signature: 126b3022bd99faba4ba78287d955c2d0
// flow-typed version: <<STUB>>/react-native-alphabetlistview_v0.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-alphabetlistview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-alphabetlistview' {
  declare module.exports: any;
}
