// flow-typed signature: ca571a7005a04f7618be5f17d1d7c7c5
// flow-typed version: <<STUB>>/react-native-paper_v2.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-paper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-paper' {
  declare module.exports: any;
}
