// flow-typed signature: d976203d5c8e64436c99703ad11082ca
// flow-typed version: <<STUB>>/react-native-network-info_v4.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-network-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-network-info' {
  declare module.exports: any;
}
