// flow-typed signature: df026ae77f56ecd285237618b69393dd
// flow-typed version: <<STUB>>/react-native-screens_v2.0.0-alpha.5/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-screens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-screens' {
  declare module.exports: any;
}
