// flow-typed signature: fcba56cf656132eb2a73525597c97481
// flow-typed version: <<STUB>>/react-native-searchbar_v1.14.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-searchbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-searchbar' {
  declare module.exports: any;
}
