// flow-typed signature: 322f79cf649d26e172c0b571a6f968ec
// flow-typed version: <<STUB>>/react-native-keychain_v0.3.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keychain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keychain' {
  declare module.exports: any;
}
