// flow-typed signature: 7b6a3b324cae9488991716c0ad66fb27
// flow-typed version: <<STUB>>/react-native-communications_v2.1.4/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-communications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-communications' {
  declare module.exports: any;
}
