// flow-typed signature: 74bbdf44643b376dba7fa4ed8e317994
// flow-typed version: <<STUB>>/react-navigation-material-bottom-tabs_v0.4.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-material-bottom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-material-bottom-tabs' {
  declare module.exports: any;
}
