// flow-typed signature: f8180cef5347a3aa223da19fbfda34d3
// flow-typed version: <<STUB>>/react-addons-shallow-compare_v15.3.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-shallow-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-shallow-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-shallow-compare/index' {
  declare module.exports: $Exports<'react-addons-shallow-compare'>;
}
declare module 'react-addons-shallow-compare/index.js' {
  declare module.exports: $Exports<'react-addons-shallow-compare'>;
}
