// flow-typed signature: 188d67ca03a88a559e61d1db48776096
// flow-typed version: <<STUB>>/react-native-custom-tabs_v0.1.7/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-custom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-custom-tabs' {
  declare module.exports: any;
}
