// flow-typed signature: 3d55cda33e6de86f43a0fd0a1dba6255
// flow-typed version: <<STUB>>/react-native-linear-gradient_v2.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

import {View} from 'react-native'
type LinearGradientProps = {
    start?: Array<number> | {x: number, y: number};
    end?: Array<number> | {x: number, y: number};
    colors: Array<string>;
    locations?: Array<number>;
} & typeof(View);

declare module 'react-native-linear-gradient' {
    declare module.exports: Class<React$Component<void, LinearGradientProps, any>>;
}
