// flow-typed signature: e2645a3e10937365bf5b62145300ae53
// flow-typed version: <<STUB>>/react-native-typography_v1.3.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-typography' {
  declare module.exports: any;
}
