// flow-typed signature: ce596e7ef70cc11860c190bb735aec36
// flow-typed version: <<STUB>>/react-native-paper_v2.16.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-paper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-paper' {
  declare module.exports: any;
}
