// flow-typed signature: b8724ecc1f697d39964ed7d1958936f8
// flow-typed version: <<STUB>>/react-native-animatable_v0.6.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-animatable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-animatable' {
  declare module.exports: any;
}
