// flow-typed signature: 108bab1764e4ef610e88f40aee52a875
// flow-typed version: <<STUB>>/react-navigation_v3.4.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation' {
  declare module.exports: any;
}
