// flow-typed signature: 48b685998b2d336920cd26a6a1eee4f0
// flow-typed version: <<STUB>>/react-markdown_v2.5.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}
