// flow-typed signature: 6e9f14d71190e9824ad87f5fbeff5abf
// flow-typed version: <<STUB>>/react-native-refreshable-listview_v1.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-refreshable-listview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-refreshable-listview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-refreshable-listview/example/renderHeaderWrapper' {
  declare module.exports: any;
}

declare module 'react-native-refreshable-listview/lib/ControlledRefreshableListView' {
  declare module.exports: any;
}

declare module 'react-native-refreshable-listview/lib/createElementFrom' {
  declare module.exports: any;
}

declare module 'react-native-refreshable-listview/lib/delay' {
  declare module.exports: any;
}

declare module 'react-native-refreshable-listview/lib/ListView' {
  declare module.exports: any;
}

declare module 'react-native-refreshable-listview/lib/RefreshableListView' {
  declare module.exports: any;
}

declare module 'react-native-refreshable-listview/lib/RefreshingIndicator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-refreshable-listview/example/renderHeaderWrapper.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/example/renderHeaderWrapper'>;
}
declare module 'react-native-refreshable-listview/index' {
  declare module.exports: $Exports<'react-native-refreshable-listview'>;
}
declare module 'react-native-refreshable-listview/index.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview'>;
}
declare module 'react-native-refreshable-listview/lib/ControlledRefreshableListView.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/lib/ControlledRefreshableListView'>;
}
declare module 'react-native-refreshable-listview/lib/createElementFrom.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/lib/createElementFrom'>;
}
declare module 'react-native-refreshable-listview/lib/delay.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/lib/delay'>;
}
declare module 'react-native-refreshable-listview/lib/ListView.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/lib/ListView'>;
}
declare module 'react-native-refreshable-listview/lib/RefreshableListView.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/lib/RefreshableListView'>;
}
declare module 'react-native-refreshable-listview/lib/RefreshingIndicator.js' {
  declare module.exports: $Exports<'react-native-refreshable-listview/lib/RefreshingIndicator'>;
}
