// flow-typed signature: 43aff2aa13655f258bb83f707c9ff755
// flow-typed version: <<STUB>>/react-native-network-info_v4.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-network-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-network-info' {
  declare module.exports: any;
}
