// flow-typed signature: 3f4c318a86fba5fc52ea86607be01442
// flow-typed version: <<STUB>>/react-native-keychain_v3.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keychain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keychain' {
  declare module.exports: any;
}
