// flow-typed signature: 4adcb472e778d22a055bfc765d6ef198
// flow-typed version: <<STUB>>/react-async_v10.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async' {
  declare module.exports: any;
}
