// flow-typed signature: 7619414459736feb6e2d93a41e3a5d2f
// flow-typed version: <<STUB>>/react-addons-shallow-compare_v15.4.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-shallow-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-shallow-compare' {
  declare module.exports: any;
}
