// flow-typed signature: 78a1e326b6f30e4ab36d7aa53350e313
// flow-typed version: <<STUB>>/react-native_v0.38.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare module.exports: any;
}
