// flow-typed signature: ca5ea5d11166701d0e23efbc11bcbec6
// flow-typed version: <<STUB>>/react-native-video_v1.0.0/flow_v0.38.0

type VideoProps = {
  source?: {uri: string} | number,
  resizeMode?: 'contain' | 'cover' | 'stretch',
  poster?: string,
  repeat?: boolean,
  paused?: boolean,
  muted?: boolean,
  volume?: number,
  rate?: number,
  playInBackground?: boolean,
  playWhenInactive?: boolean,
  ignoreSilentSwitch?: 'ignore' | 'obey',
  disableFocus?: boolean,
  controls?: boolean,
  currentTime?: number,
  progressUpdateInterval?: number,
  onLoadStart?: (e: any) => any,
  onLoad?: (e: any) => any,
  onBuffer?: (e: any) => any,
  onError?: (e: any) => any,
  onProgress?: (e: any) => any,
  onSeek?: (e: any) => any,
  onEnd?: (e: any) => any,
  onFullscreenPlayerWillPresent?: (e: any) => any,
  onFullscreenPlayerDidPresent?: (e: any) => any,
  onFullscreenPlayerWillDismiss?: (e: any) => any,
  onFullscreenPlayerDidDismiss?: (e: any) => any,
  onReadyForDisplay?: (e: any) => any,
  onPlaybackStalled?: (e: any) => any,
  onPlaybackResume?: (e: any) => any,
  onPlaybackRateChange?: (e: any) => any,
  onAudioFocusChanged?: (e: any) => any,
  onAudioBecomingNoisy?: (e: any) => any,

  scaleX?: number,
  scaleY?: number,
  translateX?: number,
  translateY?: number,
  rotation?: number,
};

// declare interface Router extends React$Component<void, RouterProps, any> {}
// declare interface Route extends React$Component<void, RouteProps, any> {}
// declare interface IndexRoute extends React$Component<void, IndexRouteProps, any> {}
// declare interface Link extends React$Component<void, LinkProps, any> {}
// declare interface IndexLink extends React$Component<void, IndexLinkProps, any> {}
// declare interface Redirect extends React$Component<void, RedirectProps, any> {}
// declare interface IndexRedirect extends React$Component<void, IndexRedirectProps, any> {}

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-video' {
  declare module.exports: Class<React$Component<void, VideoProps, any>>;
}
