// flow-typed signature: 7c58526aaaa890e7b892c1d1cec5bea0
// flow-typed version: <<STUB>>/react-native-parallax-view_v2.0.6/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-parallax-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-parallax-view' {
  declare module.exports: any;
}
