// flow-typed signature: 69a8f175f483c0c120fe4a0fbf393373
// flow-typed version: <<STUB>>/react-native-communications_v2.1.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-communications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-communications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-communications/AKCommunications' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-communications/AKCommunications.js' {
  declare module.exports: $Exports<'react-native-communications/AKCommunications'>;
}
