// flow-typed signature: 406646d16f752115eadee4207da9f41b
// flow-typed version: <<STUB>>/react-native-screens_v1.0.0-alpha.22/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-screens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-screens' {
  declare module.exports: any;
}
