// flow-typed signature: b8f504b5d7b08f314c594009883448b8
// flow-typed version: <<STUB>>/react-native-location_v2.5.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-location'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-location' {
  declare module.exports: any;
}
