// flow-typed signature: cbd705d33fc620300916fdee1778304c
// flow-typed version: <<STUB>>/react-native-animatable_v0.6.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-animatable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-animatable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-animatable/index' {
  declare module.exports: $Exports<'react-native-animatable'>;
}
declare module 'react-native-animatable/index.js' {
  declare module.exports: $Exports<'react-native-animatable'>;
}
