// flow-typed signature: 04bb1cdd173c33fdc6d9d2dd49a337e3
// flow-typed version: <<STUB>>/react-native-searchbar-controlled_v2.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-searchbar-controlled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-searchbar-controlled' {
  declare module.exports: any;
}
