// flow-typed signature: 108bab1764e4ef610e88f40aee52a875
// flow-typed version: <<STUB>>/react-navigation_v3.4.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation/NavigationTestUtils' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/__tests__/SwitchNavigator-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/react-navigation' {
  declare module.exports: any;
}

declare module 'react-navigation/src/utils/docsUrl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation/NavigationTestUtils.js' {
  declare module.exports: $Exports<'react-navigation/NavigationTestUtils'>;
}
declare module 'react-navigation/src/navigators/__tests__/SwitchNavigator-test.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/__tests__/SwitchNavigator-test'>;
}
declare module 'react-navigation/src/react-navigation.js' {
  declare module.exports: $Exports<'react-navigation/src/react-navigation'>;
}
declare module 'react-navigation/src/utils/docsUrl.js' {
  declare module.exports: $Exports<'react-navigation/src/utils/docsUrl'>;
}
