// flow-typed signature: b819f27d4cf85c6f74669e0584152778
// flow-typed version: <<STUB>>/react-native-tab-view_v0.0.40/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-view' {
  declare module.exports: any;
}
