// flow-typed signature: d662cd9e5992767deb121dec3615ab03
// flow-typed version: <<STUB>>/react-native-webview_v8.1.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webview' {
  declare module.exports: any;
}
