// flow-typed signature: 18287830e68ea00aa5d29a3bb29395fc
// flow-typed version: <<STUB>>/react-native-onesignal_v1.2.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-onesignal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-onesignal' {
  declare module.exports: any;
}
