// flow-typed signature: 57c7bec65e04787e527ef91f7c9626b4
// flow-typed version: <<STUB>>/react-native-maps_v0.20.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}
