// flow-typed signature: d25f2739d8378c927230aa40c3267f59
// flow-typed version: <<STUB>>/react-test-renderer_v15.4.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}
