// flow-typed signature: d916d5f731b562dc8f43492510e541f5
// flow-typed version: <<STUB>>/react-native-tableview-simple_v0.13.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tableview-simple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tableview-simple' {
  declare module.exports: any;
}
