// flow-typed signature: 905d61a3ced141855e301ad3273a22af
// flow-typed version: <<STUB>>/react-navigation-material-bottom-tabs_v1.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-material-bottom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-material-bottom-tabs' {
  declare module.exports: any;
}
