// flow-typed signature: e0863b9b8c931cc0f770ca79b6441f53
// flow-typed version: <<STUB>>/react-native-popover-view_v1.0.19/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popover-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popover-view' {
  declare module.exports: any;
}
