// flow-typed signature: 04d84490a03d5813f73bc861b1e8a019
// flow-typed version: <<STUB>>/react-native-typography_v1.4.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-typography' {
  declare module.exports: any;
}
