// flow-typed signature: 8ad8e8caa432af2295b78420b16b14c7
// flow-typed version: <<STUB>>/react-native-tab-view_v0.0.40/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-view' {
  declare module.exports: any;
}
