// flow-typed signature: 85c626395184f14bfb4cddffdbfa2fef
// flow-typed version: <<STUB>>/react-native-onesignal_v1.2.3/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-onesignal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-onesignal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-onesignal/index' {
  declare module.exports: $Exports<'react-native-onesignal'>;
}
declare module 'react-native-onesignal/index.js' {
  declare module.exports: $Exports<'react-native-onesignal'>;
}
