// flow-typed signature: fc8fd4fa7a47a333939f3f83d688bb0a
// flow-typed version: <<STUB>>/react-native-search-bar_v3.4.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-search-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-search-bar' {
  declare module.exports: any;
}
