// flow-typed signature: a88e9019b2b9f901060329227b012b2b
// flow-typed version: <<STUB>>/react-native-network-info_v3.0.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-network-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-network-info' {
  declare module.exports: any;
}
