// flow-typed signature: 2656a380e42b11a5d4b0a786d0bd9698
// flow-typed version: <<STUB>>/react-native-popover-view_v1.0.19/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popover-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popover-view' {
  declare module.exports: any;
}
