// flow-typed signature: 5e01bca0a4c5b03a457bb5cac610c8a2
// flow-typed version: <<STUB>>/react-native-location_v2.5.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-location'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-location' {
  declare module.exports: any;
}
