// flow-typed signature: 49c5bd8aa79d4ebbbb6f7b3af5f26306
// flow-typed version: <<STUB>>/redux-thunk_v2.3.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}
