// flow-typed signature: 93b99787be227e2c8dcd4fe5abf15bc4
// flow-typed version: <<STUB>>/redux-logger_v3.0.6/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}
