// flow-typed signature: 4e4df6af6478967332e66fcec0b05e14
// flow-typed version: <<STUB>>/redux-thunk_v2.3.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}
