// flow-typed signature: a6af5604fb39c468d5164c6da6b18a61
// flow-typed version: <<STUB>>/redux-promise_v0.6.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise' {
  declare module.exports: any;
}
