// flow-typed signature: 9e55b2788d5e4987987a20e6eb567073
// flow-typed version: <<STUB>>/redux-logger_v2.7.4/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}
