// flow-typed signature: 5c9a6cf906fb0253ed4a2f89777d8b6b
// flow-typed version: <<STUB>>/semver_v7.3.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver' {
  declare module.exports: any;
}
