// flow-typed signature: bc0ffb08dc975a625de485e2fc7e39cb
// flow-typed version: <<STUB>>/sto-sis-time-parser_v2.3.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sto-sis-time-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sto-sis-time-parser' {
  declare module.exports: any;
}
