// flow-typed signature: d1bff06fcefabacabeee88ab5097c3db
// flow-typed version: <<STUB>>/stream_v0.0.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream' {
  declare module.exports: any;
}
