// flow-typed signature: cd1e78b77209a27cffa419e9acad64d7
// flow-typed version: <<STUB>>/stream_v0.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream' {
  declare module.exports: any;
}
