// flow-typed signature: 6a2dfe46defc7975d168426fef7e9a2f
// flow-typed version: <<STUB>>/strip-ansi_v4.0.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-ansi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-ansi' {
  declare module.exports: any;
}
