// flow-typed signature: 0c6ad97ba07684dec4dd9d296ce9a533
// flow-typed version: <<STUB>>/strip-ansi_v5.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-ansi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-ansi' {
  declare module.exports: any;
}
