// flow-typed signature: 1ec011c992e9932cbc7c09b319522f14
// flow-typed version: <<STUB>>/strip-ansi_v5.2.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-ansi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-ansi' {
  declare module.exports: any;
}
