// flow-typed signature: 8b9be22bee38dd729be4b64ea56135a7
// flow-typed version: <<STUB>>/timers_v0.1.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timers' {
  declare module.exports: any;
}
