// flow-typed signature: 5ccc4e2d9a0df3633585557bc66f9709
// flow-typed version: <<STUB>>/tinycolor2_v1.4.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinycolor2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinycolor2' {
  declare module.exports: any;
}
