// flow-typed signature: a4c60850f0936a8d72185fbc5fb5ce5c
// flow-typed version: <<STUB>>/tinycolor2_v1.4.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinycolor2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinycolor2' {
  declare module.exports: any;
}
