// flow-typed signature: 7763727e48152ab0c764f451c7c12a76
// flow-typed version: <<STUB>>/titlecase_v1.1.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'titlecase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'titlecase' {
  declare module.exports: any;
}
