// flow-typed signature: 8d08266694ce02c7d4c0b2a0b175ba02
// flow-typed version: <<STUB>>/url_v0.11.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url' {
  declare module.exports: any;
}
