// flow-typed signature: 9ac7c9f65afd0fc6544c9cf6cc653907
// flow-typed version: <<STUB>>/url_v0.11.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url' {
  declare module.exports: any;
}
