// flow-typed signature: b2384be119554ca55be1f1dda87a5e5a
// flow-typed version: <<STUB>>/url_v0.11.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url' {
  declare module.exports: any;
}
