// flow-typed signature: be075c3bce7a00fa6dd3c72c5610851c
// flow-typed version: <<STUB>>/wordwrap_v1.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wordwrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wordwrap' {
  declare module.exports: any;
}
