// flow-typed signature: 2de4822cb6783daef35a2d66a2b0ec9d
// flow-typed version: <<STUB>>/wordwrap_v1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wordwrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wordwrap' {
  declare module.exports: any;
}
