// flow-typed signature: 482da21fc54c5067a4aac2e85092d63b
// flow-typed version: <<STUB>>/xcode_v1.0.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xcode' {
  declare module.exports: any;
}
