// flow-typed signature: 59defb0a720fe729c12f5aa39f6c4506
// flow-typed version: <<STUB>>/xcode_v1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xcode' {
  declare module.exports: any;
}
