// flow-typed signature: 57a0ca8be605ed1a3ea828e8270d244a
// flow-typed version: <<STUB>>/xcode_v1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xcode' {
  declare module.exports: any;
}
