// flow-typed signature: dd5bb994d1775e9916fee0a5b1c0dad1
// flow-typed version: <<STUB>>/xml2js_v0.4.17/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xml2js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xml2js' {
  declare module.exports: any;
}
