// flow-typed signature: f14b9b94ca26d272f5bacd2cb1aac07e
// flow-typed version: <<STUB>>/xml2js_v0.4.19/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xml2js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xml2js' {
  declare module.exports: any;
}
