// flow-typed signature: a6f2d5a950e0d764694cb33d77d3d137
// flow-typed version: <<STUB>>/xml2js_v0.4.17/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xml2js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xml2js' {
  declare module.exports: any;
}
