// flow-typed signature: 568b8300f10b8d6430ba5c75cc8025bd
// flow-typed version: <<STUB>>/yarn-deduplicate_v2.1.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-deduplicate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-deduplicate' {
  declare module.exports: any;
}
