// flow-typed signature: 04a35992b850eeb868518b4edd1fb025
// flow-typed version: <<STUB>>/yarn-deduplicate_v1.1.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-deduplicate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-deduplicate' {
  declare module.exports: any;
}
