// flow-typed signature: 876bef58ec6a5abdad5853fcbd916ddc
// flow-typed version: <<STUB>>/yarn-deduplicate_v1.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-deduplicate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-deduplicate' {
  declare module.exports: any;
}
