// flow-typed signature: 5a611931c071f494be6e63208d81afa4
// flow-typed version: <<STUB>>/@babel/core_v7.6.4/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/core' {
  declare module.exports: any;
}
