// flow-typed signature: 8286f18309b6c89263fdf3c92c0ae508
// flow-typed version: <<STUB>>/@babel/core_v7.3.4/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/core' {
  declare module.exports: any;
}
