// flow-typed signature: e316d9cfcdd9e2d50289e523a034cfbc
// flow-typed version: <<STUB>>/@babel/core_v7.10.5/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/core' {
  declare module.exports: any;
}
