// flow-typed signature: 8245aa17e60afc6888fc8d983efcb7b4
// flow-typed version: <<STUB>>/@babel/runtime_v7.6.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/runtime' {
  declare module.exports: any;
}
