// flow-typed signature: 8b491a5bbcb2b977c7125de02cce76f0
// flow-typed version: <<STUB>>/@babel/runtime_v7.10.5/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/runtime' {
  declare module.exports: any;
}
