// flow-typed signature: c4538c4674a50cb45b6a056addf458a7
// flow-typed version: <<STUB>>/@babel/runtime_v^7.3.4/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/runtime' {
  declare module.exports: any;
}
