version: 2

workflows:
  version: 2
  analyze:
    jobs:
      - danger
      - flow
      - jest
      - prettier
      - eslint
      - data

jobs:
  danger:
    docker: [{image: 'circleci/node:8'}]
    steps:
      - checkout
      - restore_cache: &restore-cache-yarn
          keys:
            - 'v1-dependencies-{{ checksum "yarn.lock" }}'
            - v1-dependencies-
      - run: yarn install
      - save_cache: &save-cache-yarn
          paths: [node_modules]
          key: 'v1-dependencies-{{ checksum "yarn.lock" }}'
      - run: echo yarn danger --id JS-general

  flow:
    docker: [{image: 'circleci/node:8'}]
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: yarn bundle-data
      - run: yarn flow check --quiet

  jest:
    docker: [{image: 'circleci/node:8'}]
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: yarn bundle-data
      - run: yarn test --coverage

  prettier:
    docker: [{image: 'circleci/node:8'}]
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: yarn prettier

  eslint:
    docker: [{image: 'circleci/node:8'}]
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: yarn bundle-data
      - run: yarn lint

  data:
    docker: [{image: 'circleci/node:8'}]
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: yarn validate-data --quiet
      - run: yarn validate-bus-data
