version: 2

x-config:
  - &restore-cache-yarn
    keys:
      - 'v2-dependencies-{{ checksum "yarn.lock" }}'
      - 'v2-dependencies-'
  - &save-cache-yarn
    paths: [~/.cache/yarn]
    key: 'v2-dependencies-{{ checksum "yarn.lock" }}'
  - &restore-cache-bundler
    keys:
      - 'v1-dependencies-{{ checksum "Gemfile.lock" }}'
      - 'v1-dependencies-'
  - &save-cache-bundler
    paths: [./vendor/bundle]
    key: 'v1-dependencies-{{ checksum "Gemfile.lock" }}'
  - &run-danger
    command: yarn run danger --id $task
    when: always

workflows:
  version: 2
  analyze:
    jobs:
      - danger
      - flow
      - jest
      - prettier
      - eslint
      - data
      - ios: {requires: [danger, flow, jest, prettier, eslint, data]}
      - android: {requires: [danger, flow, jest, prettier, eslint, data]}

jobs:
  danger:
    docker: [{image: 'circleci/node:8'}]
    environment: {task: JS-general}
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: *run-danger

  flow:
    docker: [{image: 'circleci/node:8'}]
    environment: {task: JS-flow}
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: mkdir -p logs/
      - run: yarn run bundle-data
      - run: yarn run --silent flow check --quiet | tee logs/flow
      - run: *run-danger

  jest:
    docker: [{image: 'circleci/node:8'}]
    environment: {task: JS-jest}
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: mkdir -p logs/
      - run: yarn run bundle-data
      - run: yarn run --silent test --coverage 2>&1 | tee logs/jest
      - run: *run-danger
      - run: yarn global add coveralls
      - run:
          name: coveralls
          command: |
            export PATH=$PATH:$(yarn global bin)
            export COVERALLS_SERVICE_NAME=CircleCI
            export COVERALLS_SERVICE_JOB_ID=$CIRCLE_BUILD_NUM
            coveralls < ./coverage/lcov.info

  prettier:
    docker: [{image: 'circleci/node:8'}]
    environment: {task: JS-prettier}
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: mkdir -p logs/
      - run: yarn run prettier
      - run:
          name: git diff
          command: |
            touch logs/prettier  # to ensure that the file exists
            if ! git diff --quiet *.js source/ scripts/; then
              git diff *.js source/ scripts/ | tee logs/prettier
            fi
      - run: *run-danger

  eslint:
    docker: [{image: 'circleci/node:8'}]
    environment: {task: JS-lint}
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: mkdir -p logs/
      - run: yarn run bundle-data
      - run: yarn run --silent lint | tee logs/eslint
      - run: *run-danger

  data:
    docker: [{image: 'circleci/node:8'}]
    environment: {task: JS-data}
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - run: mkdir -p logs/
      - run: yarn run --silent validate-data --quiet | tee logs/validate-data
      - run: yarn run --silent validate-bus-data | tee logs/validate-bus-data
      - run: *run-danger

  android:
    docker: [{image: 'circleci/android:api-27-node8-alpha'}]
    environment: {task: ANDROID}
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4.2" > ~/.ruby-version
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - restore_cache: *restore-cache-bundler
      - run: bundle check || bundle install --path ./vendor/bundle
      - save_cache: *save-cache-bundler
      - run: mkdir -p logs/
      - run: touch .env.js
      - run: bundle exec fastlane android ci-run | tee ./logs/build
      - run: *run-danger

  ios:
    macos: {xcode: '9.2'}
    environment: {task: IOS}
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4.2" > ~/.ruby-version
      - restore_cache: *restore-cache-yarn
      - run: yarn install
      - save_cache: *save-cache-yarn
      - restore_cache: *restore-cache-bundler
      - run: bundle check || bundle install --path ./vendor/bundle
      - save_cache: *save-cache-bundler
      - run: mkdir -p logs/
      - run: touch .env.js
      - run: bundle exec fastlane ios ci-run | tee ./logs/build
      - run:
          name: Analyze Fastlane Logfile
          commane: python2 ./scripts/analyze-gym.py -s 20 < ./logs/build | tee ./logs/analysis || true
      - run: *run-danger
