---
version: 2.1

executors:
  node: {docker: [{image: 'circleci/node:10'}]}

  ruby: {docker: [{image: 'circleci/ruby:2.5.5'}]}

  # we pass the `command:` key to solve a weird issue (see GitHub PRs 2170 and
  # 2173). this overrides the thing and forces the container to run /bin/bash
  # as the "command" so it doesn't get confused and OOM/exhaust the build
  # resources (I have no better explanations.)
  android:
    docker: [{image: 'circleci/android:api-28-node', command: '/bin/bash'}]
    environment:
      GRADLE_USER_HOME: &gradle-home ~/.gradle
      SENTRY_PROPERTIES: ../android/sentry.properties

  ios:
    macos: {xcode: '10.2.1'}
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      SENTRY_PROPERTIES: '../ios/sentry.properties'

x-environment: &x-environment
  FASTLANE_SKIP_UPDATE_CHECK: '1'
  FASTLANE_DISABLE_ANIMATION: '1'
  HOMEBREW_NO_AUTO_UPDATE: '1'

  # The bundle identifier of your app
  APP_IDENTIFIER: &app-id 'NFMTHAZVS9.com.drewvolz.stolaf'

  # Your Apple email address
  APPLE_ID: 'aao_bot@fastmail.fm'
  APPLE_DEV_PORTAL_ID: 'hawkrives@gmail.com'

  # Your Apple Developer Team ID, if you are in multiple teams
  TEAM_ID: &team-id 'TMK6S7TPX2'
  ITC_TEAM_ID: '118781268'
  PILOT_ITC_PROVIDER: *team-id

  # This is a private key. It is not included in the repository.
  # Contact allaboutolaf@stolaf.edu or another admin if you need access.
  JSON_KEY_FILE: './fastlane/play-private-key.json'
  PACKAGE_NAME: 'com.allaboutolaf'

  # set up global info for `gym`
  GYM_PROJECT: './ios/AllAboutOlaf.xcodeproj'
  IOS_INFO_PLIST: './ios/AllAboutOlaf/Info.plist'
  GYM_SCHEME: 'AllAboutOlaf'
  GYM_OUTPUT_DIRECTORY: './ios/build'
  GYM_OUTPUT_NAME: 'AllAboutOlaf'
  GYM_ARCHIVE_PATH: './ios/archive/app.xcarchive'

  GRADLE_FILE: './android/app/build.gradle'
  KEYSTORE_FILE: './android/app/upload-keystore.properties'

  # set up other global shared values
  PRETTY_APP_NAME: 'All About Olaf'
  ONESIGNAL_APP_NAME: 'All About Olaf'
  ONESIGNAL_APP_ID: 'a46c6f2f-a240-4908-a359-801911e9b9ea'
  APPLE_APP_ID: *app-id
  APPLE_APP_NAME: 'All About Olaf'
  APPLE_PUSH_EXTENSION_ID: 'NFMTHAZVS9.com.drewvolz.stolaf.onesignal-notification-service-extension'
  APPLE_PUSH_EXTENSION_NAME: 'All About Olaf OneSignal Notification Service Extension'

  BUNDLER_CACHE_DIR: &bundler-cache-path './.bundle'
  YARN_CACHE_DIR: &yarn-cache-path '~/.yarn'

commands:
  bundler-cache:
    description: 'Save the Bundler cache'
    steps:
      - save_cache:
          key: &bundler-cache-key >-
            v4-ruby-dependencies
            {{ arch }}
            {{ checksum "Gemfile.lock" }}
          paths: [*bundler-cache-path]

  bundler-restore:
    description: 'Restore the Bundler cache'
    steps:
      - restore_cache: {key: *bundler-cache-key}

  gradle-cache:
    description: 'Save the Gradle cache'
    steps:
      - save_cache:
          key: &gradle-cache-key >-
            v2-gradle-dependencies
            {{ arch }}
            {{ checksum "android/gradle/wrapper/gradle-wrapper.properties" }}
            {{ checksum "android/build.gradle" }}
            {{ checksum "android/settings.gradle" }}
            {{ checksum "android/app/build.gradle" }}
            {{ checksum "node_modules/react-native/package.json" }}
          paths: [~/.gradle]

  gradle-restore:
    description: 'Restore the Gradle cache'
    steps:
      - restore_cache: {key: *gradle-cache-key}

  yarn-cache:
    description: 'Save the Yarn cache'
    steps:
      - save_cache:
          key: &yarn-cache-key >-
            v4-yarn-dependencies
            {{ arch }}
            {{ checksum "yarn.lock" }}
          paths: [*yarn-cache-path, ./node_modules]

  yarn-restore:
    description: 'Restore the Yarn cache'
    steps:
      - restore_cache: {key: *yarn-cache-key}

  logs-cache:
    description: 'cache the ./logs folder'
    steps:
      - save_cache:
          key: &logs-cache-key >-
            v1-logs
            {{ arch }}
            {{ epoch }}
          paths: [./logs]

  logs-restore:
    description: 'Restore the logs'
    steps:
      - restore_cache: {key: *logs-cache-key}

  set-ruby-version:
    description: 'Set the Ruby Version'
    steps:
      - run: echo "ruby-2.5.5" > ~/.ruby-version

  danger:
    description: 'Run Danger'
    steps:
      - run:
          name: "danger"
          command: |
            if ! [[ $CIRCLE_PR_NUMBER ]]; then
              yarn run danger --id $task;
            fi
          when: always
          environment:
            DANGER_DISABLE_TRANSPILATION: 'true'

  reconcile-git-history:
    description: "Fix CircleCI's git history"
    steps:
      - run:
          name: 'Reconcile Git histories'
          command: |
            if [ -z "$CIRCLE_TAG" ];
            then
              git checkout master
              git reset --hard origin/master
              git checkout "$CIRCLE_BRANCH"
              git reset --hard "origin/$CIRCLE_BRANCH"
            else
              echo "CIRCLE_TAG was set, didn't do anything"
            fi

  yarn-install:
    steps:
      - run: yarn --version
      - run:
          name: 'yarn install'
          command: yarn install --frozen-lockfile --prefer-offline --cache-folder "$YARN_CACHE_DIR"

  bundler-install:
    steps:
      - run: gem install bundler
      - run: bundle --version
      - run:
          name: 'bundle install'
          command: bundle install --frozen --path "$BUNDLER_CACHE_DIR"

  skip-if-possible:
    description: "Skip the build, if possible"
    steps:
      - run:
          name: Skip build if possible
          command: ./scripts/ci/should-skip-build && circleci step halt || echo "Build continuing."

  coveralls:
    description: 'Run Coveralls'
    steps:
      - run:
          name: coveralls
          command: |
            export COVERALLS_SERVICE_NAME="CircleCI"
            export COVERALLS_SERVICE_JOB_ID="$CIRCLE_BUILD_NUM"
            if ! [[ $CIRCLE_PR_NUMBER ]]; then
              npx coveralls < ./coverage/lcov.info
            fi

x-tag-filters: &filters {tags: {only: /.*/}}

workflows:
  version: 2
  analyze-and-build:
    jobs: &basic-jobs
      - ios-prepare: {filters: *filters}
      - ios-build: {filters: *filters, requires: [ios-prepare]}
      - ios-deploy: {filters: *filters, requires: [ios-build]}

      - android-prepare: {filters: *filters}
      - android-build: {filters: *filters, requires: [android-prepare]}
      - android-deploy: {filters: *filters, requires: [android-build]}

jobs:
  android-prepare: &android-base
    executor: android
    environment: &android-env
      <<: *x-environment
      task: ANDROID-prepare
    steps:
      - checkout
      - skip-if-possible

      - yarn-restore
      - yarn-install
      - yarn-cache

      - set-ruby-version
      - run: ruby --version
      - run: gem --version
      - bundler-restore
      - bundler-install
      - bundler-cache

      - run: cd android && ./gradlew --version
      # - gradle-restore
      - run:
          name: Download Android dependencies
          command: cd android && ./gradlew androidDependencies --console=plain
          environment:
            TERM: xterm-256color
      - gradle-cache

  android-build: &android-build
    <<: *android-base
    environment: &android-build-env
      <<: *android-env
      task: ANDROID-build
    steps:
      - checkout
      - reconcile-git-history
      - skip-if-possible

      - set-ruby-version
      - bundler-restore
      - yarn-restore
      - gradle-restore

      - run:
          name: 'Restrict Gradle parallelization'
          command: echo 'org.gradle.workers.max=2' >> ./android/gradle.properties
      - run:
          name: 'Propagate app version into build files'
          command: bundle exec ./scripts/ci/propagate-version.rb
      - run:
          name: 'Authorize CI for keys, if allowed'
          command: if ./scripts/ci/is-signed.sh; then bundle exec ./scripts/ci/authorize-ci-for-keys.rb; fi
      - run:
          name: 'Install certificates, if allowed'
          command: if ./scripts/ci/is-signed.sh; then ./scripts/ci/android/certificates.sh; fi

      - run: mkdir -p logs/

      - run:
          name: 'Build app'
          command: |
            cd ./android && ./gradlew bundleRelease && cd -
            echo $? > logs/build-status

      - run:
          name: 'Discover generated products'
          command: ./scripts/ci/android/discover-products.sh | tee ./logs/products

      # eventually, implement detox for android

      - persist_to_workspace:
          root: ./android/build
          paths: [./*]

      - logs-cache

      - danger

  android-deploy:
    <<: *android-base
    environment:
      <<: *android-env
      task: ANDROID-deploy
    steps:
      - checkout
      - reconcile-git-history
      - skip-if-possible

      - set-ruby-version
      - bundler-restore

      - logs-restore

      - attach_workspace:
          at: ./android/build

      - run:
          name: '[nightly/beta] upload to Play Store'
          command: |
            if ./scripts/ci/is-beta.sh; then
              TRACK=beta
            else if ./scripts/ci/is-nightly.sh; then
              TRACK=alpha
            fi

            if [[ -n $TRACK ]]; then
              bundle exec fastlane run upload_to_play_store
                --aab "$(paste -sd ',' < ./logs/products)"
                --check_superseded_tracks true
                --track "$TRACK"
            fi

      - yarn-restore

      - run:
          name: '[nightly/beta] generate and upload sourcemaps'
          command: |
            if [[ ./scripts/ci/is-nightly.sh || ./scripts/ci/is-beta.sh ]]; then
              ./scripts/ci/sourcemap-create.sh
              ./scripts/ci/sourcemap-upload.sh
            fi

      - danger

  ios-prepare: &ios-base
    executor: ios
    environment: &ios-env
      <<: *x-environment
      task: IOS-prepare
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - reconcile-git-history
      - skip-if-possible

      - yarn-restore
      - yarn-install
      - yarn-cache

      - set-ruby-version
      - run: ruby --version
      - run: gem --version
      - bundler-restore
      - bundler-install
      - bundler-cache

  ios-build: &ios-build
    <<: *ios-base
    environment: &ios-build-env
      <<: *ios-env
      task: IOS-build
    steps:
      - checkout
      - reconcile-git-history
      - skip-if-possible

      - set-ruby-version
      - bundler-restore
      - yarn-restore

      - run:
          name: 'Show Xcode build settings'
          command: |
            if [[ ./scripts/ci/is-nightly.sh || ./scripts/ci/is-beta.sh ]]; then
              xcodebuild -scheme "$GYM_SCHEME" -project "$GYM_PROJECT" -showBuildSettings
            else
              xcodebuild -scheme "$GYM_SCHEME" -project "$GYM_PROJECT" -showBuildSettings -derivedDataPath ./ios/build
            fi

      - run:
          name: 'Propagate app version into build files'
          command: bundle exec ./scripts/ci/propagate-version.rb
      - run:
          name: 'Authorize CI for keys, if allowed'
          command: if ./scripts/ci/is-signed.sh; then bundle exec ./scripts/ci/authorize-ci-for-keys.rb; fi
      - run:
          name: 'Install certificates, if allowed'
          command: if ./scripts/ci/is-signed.sh; then ./scripts/ci/ios/certificates.sh; fi

      - run: mkdir -p logs/

      - run:
          name: 'Discover generated products'
          command: ./scripts/ci/ios/discover-products.sh | tee ./logs/products

      - run:
          name: 'Build app for simulator testing'
          command: xcodebuild
            -scheme "$GYM_SCHEME" -project "$GYM_PROJECT"
            -configuration Release
            -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.2'
            -derivedDataPath ./ios/build
            CODE_SIGNING_REQUIRED=NO
            CODE_SIGNING_ALLOWED=NO
            CODE_SIGN_IDENTITY=""
            build | xcpretty

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run:
          name: 'Run Detox tests'
          command: yarn detox test e2e --configuration ios.sim.release --cleanup

      - run:
          name: 'Build app for release [nightly/beta]'
          command: |
            if [[ ./scripts/ci/is-nightly.sh || ./scripts/ci/is-beta.sh ]]; then
              xcodebuild -scheme "$GYM_SCHEME" -project "$GYM_PROJECT"
                -destination generic/platform=iOS
                -archivePath "$GYM_ARCHIVE_PATH"
                archive | xcpretty
            fi

      - persist_to_workspace: {root: ./ios/archive, paths: [./*]}

      - logs-cache

  ios-deploy:
    <<: *ios-base
    environment:
      <<: *ios-env
      task: IOS-deploy
    steps:
      - checkout
      - reconcile-git-history
      - skip-if-possible

      - set-ruby-version
      - bundler-restore

      - attach_workspace: {at: ./ios/archive}

      - logs-restore

      - run:
          name: '[nightly/beta] upload to Play Store'
          command: |
            if ./scripts/ci/is-beta.sh; then
              EXTERNAL=true
            else if ./scripts/ci/is-nightly.sh; then
              EXTERNAL=false
            fi

            if [[ -n $EXTERNAL ]]; then
              bundle exec fastlane run upload_to_testflight
                --distribute_external $EXTERNAL
                --ipa $(cat ./logs/products)
            fi

      - yarn-restore

      - run:
          name: '[nightly/beta] generate and upload sourcemaps'
          command: |
            if [[ ./scripts/ci/is-nightly.sh || ./scripts/ci/is-beta.sh ]]; then
              ./scripts/ci/sourcemap-create.sh
              ./scripts/ci/sourcemap-upload.sh
            fi

      - danger

  android-build-nightly:
    <<: *android-build
    environment:
      <<: *android-build-env
      IS_NIGHTLY: '1'

  ios-build-nightly:
    <<: *ios-build
    environment:
      <<: *ios-build-env
      IS_NIGHTLY: '1'
