// @flow

import * as c from './components/colors'

export type ViewType =
	| {
			type: 'view',
			view: string,
			title: string,
			icon: string,
			foreground: 'light' | 'dark',
			gradient?: [string, string],
	  }
	| {
			type: 'url',
			view: string,
			url: string,
			title: string,
			icon: string,
			foreground: 'light' | 'dark',
			gradient?: [string, string],
	  }

export const allViews: ViewType[] = [
	{
		type: 'view',
		view: 'MenusView',
		title: 'Food',
		icon: 'bowl',
		foreground: 'light',
		gradient: c.grassToLime,
		size: {width: 1, height: 1},
	},
	{
		type: 'url',
		url: 'https://www.stolaf.edu/personal/index.cfm',
		view: 'DirectoryView',
		title: 'Directory',
		icon: 'v-card',
		foreground: 'light',
		gradient: c.redToPurple,
		size: {width: 1, height: 1},
	},
	{
		type: 'widget',
		view: '/me/balances/',
		title: 'Balances',
		icon: 'credit',
		size: {width: 2, height: 2},
	},
	{
		type: 'view',
		view: 'RadioView',
		title: 'Radio',
		icon: 'radio',
		// icon: 'mic',
		foreground: 'light',
		gradient: c.kstoToKsto,
		size: {width: 1, height: 1},
	},
	{
		type: 'url',
		url: 'https://moodle.stolaf.edu/',
		view: 'MoodleView',
		title: 'Moodle',
		icon: 'graduation-cap',
		foreground: 'light',
		gradient: c.yellowToGoldLight,
		size: {width: 1, height: 1},
	},
	{
		type: 'widget',
		view: '/dictionary/term-of-the-day/',
		title: 'Term of the Day',
		icon: 'new',
		size: {width: 3, height: 2},
	},
	{
		type: 'view',
		view: 'StudentOrgsView',
		title: 'Orgs',
		icon: 'globe',
		foreground: 'light',
		gradient: c.tealToSeafoam,
		size: {width: 1, height: 1},
	},
	{
		type: 'url',
		url: 'https://www.myatlascms.com/map/index.php?id=294',
		view: 'MapView',
		title: 'Map',
		icon: 'map',
		foreground: 'light',
		gradient: c.navyToNavy,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'SISView',
		title: 'Me',
		icon: 'fingerprint',
		foreground: 'light',
		gradient: c.yellowToGoldDark,
		size: {width: 2, height: 1},
	},
	{
		type: 'view',
		view: 'CalendarView',
		title: 'Happening',
		icon: 'calendar',
		foreground: 'light',
		gradient: c.magentaToPurple,
		size: {width: 2, height: 1},
	},
	{
		type: 'view',
		view: 'BuildingHoursView',
		title: 'Hours',
		icon: 'clock',
		foreground: 'light',
		gradient: c.lightBlueToBlueDark,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'StreamingView',
		title: 'Streaming',
		icon: 'video',
		foreground: 'light',
		gradient: c.lightBlueToBlueLight,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'WeeklyMovieView',
		title: 'Movie',
		icon: 'ticket', //'clapperboard',
		foreground: 'light',
		gradient: c.grayToBlack,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'ContactsView',
		title: 'Contacts',
		icon: 'phone',
		foreground: 'light',
		gradient: c.orangeToRed,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'NewsView',
		title: 'News',
		icon: 'news',
		foreground: 'light',
		gradient: c.purpleToIndigo,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'TransportationView',
		title: 'Transit',
		icon: 'address',
		foreground: 'light',
		gradient: c.grayToDarkGray,
		size: {width: 1, height: 1},
	},
	{
		type: 'widget',
		view: '/transit/upcoming/?route=northfield-express',
		title: 'Northfield Express',
		icon: 'flow-line',
		size: {width: 2, height: 2},
	},
	{
		type: 'view',
		view: 'HelpView',
		title: 'Help',
		icon: 'help',
		foreground: 'light',
		gradient: c.seafoamToGrass,
		size: {width: 1, height: 1},
	},
	{
		type: 'view',
		view: 'DictionaryView',
		title: 'Dictionary',
		icon: 'open-book',
		foreground: 'light',
		gradient: c.pinkToHotpink,
		size: {width: 1, height: 1},
	},
]

export const allViewNames = allViews.map(v => v.view)
