// @flow

import * as c from '@frogpond/colors'
import {type EntypoGlyphs} from 'react-native-vector-icons/Entypo'

export type ViewType =
	| {
			type: 'view',
			view: string,
			title: string,
			icon: EntypoGlyphs,
			foreground: 'light' | 'dark',
			tint: string,
	  }
	| {
			type: 'url',
			view: string,
			url: string,
			title: string,
			icon: EntypoGlyphs,
			foreground: 'light' | 'dark',
			tint: string,
	  }
	| {
			type: 'external-url',
			view: string,
			url: string,
			title: string,
			icon: EntypoGlyphs,
			foreground: 'light' | 'dark',
			tint: string,
	  }

export const groupedViews: Map<string, Array<ViewType>> = new Map([
	[
		'Menus',
		[
			{
				type: 'view',
				view: 'MenusView',
				title: 'Stav Hall',
				icon: 'bowl',
				foreground: 'light',
				tint: c.emerald,
			},
			{
				type: 'view',
				view: 'MenusView',
				title: 'The Cage',
				icon: 'bowl',
				foreground: 'light',
				tint: c.emerald,
			},
		],
	],
	[
		'xyz',
		[
			{
				type: 'view',
				view: 'SISView',
				title: 'OleCard Balances',
				icon: 'fingerprint',
				foreground: 'light',
				tint: c.goldenrod,
			},
			{
				type: 'view',
				view: 'BuildingHoursView',
				title: 'Building Hours',
				icon: 'clock',
				foreground: 'light',
				tint: c.wave,
			},
			{
				type: 'view',
				view: 'CalendarView',
				title: 'Calendar',
				icon: 'calendar',
				foreground: 'light',
				tint: c.coolPurple,
			},
			{
				type: 'view',
				view: 'StreamingView',
				title: 'Viking Movie',
				icon: 'video',
				foreground: 'light',
				tint: c.denim,
			},
		],
	],
	[
		'Hubs',
		[
			{
				type: 'url',
				url: 'https://oleville.com/pause',
				view: 'MapView',
				title: 'The Pause',
				icon: 'bowl',
				foreground: 'light',
				tint: c.coffee,
			},
			{
				type: 'view',
				view: 'StreamingView',
				title: 'KSTO / Radio',
				icon: 'video',
				foreground: 'light',
				tint: c.denim,
			},
			{
				type: 'view',
				view: 'NewsView',
				title: 'Oleville',
				icon: 'news',
				foreground: 'light',
				tint: c.eggplant,
			},
			{
				type: 'view',
				view: 'NewsView',
				title: 'The Manitou Messenger',
				icon: 'news',
				foreground: 'light',
				tint: c.eggplant,
			},
			{
				type: 'view',
				view: 'StreamingView',
				title: 'Broadcast Media',
				icon: 'video',
				foreground: 'light',
				tint: c.denim,
			},
			{
				type: 'url',
				url: 'https://www.stolaf.edu/library',
				view: 'MapView',
				title: 'Library',
				icon: 'open-book',
				foreground: 'light',
				tint: c.coffee,
			},
		],
	],
	[
		'Campus',
		[
			{
				type: 'view',
				view: 'DictionaryView',
				title: 'Dictionary',
				icon: 'open-book',
				foreground: 'light',
				tint: c.olive,
			},
			{
				type: 'url',
				url: 'https://www.myatlascms.com/map/index.php?id=294',
				view: 'MapView',
				title: 'Campus Map',
				icon: 'map',
				foreground: 'light',
				tint: c.coffee,
			},
			{
				type: 'view',
				view: 'NewsView',
				title: 'Campus News',
				icon: 'news',
				foreground: 'light',
				tint: c.eggplant,
			},
			{
				type: 'url',
				url: 'https://www.stolaf.edu/personal/index.cfm',
				view: 'DirectoryView',
				title: 'Directory',
				icon: 'v-card',
				foreground: 'light',
				tint: c.indianRed,
			},
			{
				type: 'view',
				view: 'TransportationView',
				title: 'Getting Around Northfield',
				icon: 'address',
				foreground: 'light',
				tint: c.cardTable,
			},
			{
				type: 'view',
				view: 'TransportationView',
				title: 'To Minneapolis or Elsewhere',
				icon: 'address',
				foreground: 'light',
				tint: c.cardTable,
			},
		],
	],
	[
		'Student',
		[
			{
				type: 'view',
				view: 'SISView',
				title: 'Class/Lab Schedule',
				icon: 'fingerprint',
				foreground: 'light',
				tint: c.goldenrod,
			},
			{
				type: 'view',
				view: 'PrintJobsView',
				title: 'stoPrint',
				icon: 'print',
				foreground: 'light',
				tint: c.periwinkle,
			},
			{
				type: 'url',
				url: 'https://moodle.stolaf.edu/',
				view: 'MoodleView',
				title: 'Moodle',
				icon: 'graduation-cap',
				foreground: 'light',
				tint: c.cantaloupe,
			},
			{
				type: 'view',
				view: 'SISView',
				title: 'Time Entry System',
				icon: 'fingerprint',
				foreground: 'light',
				tint: c.goldenrod,
			},
			{
				type: 'view',
				view: 'SISView',
				title: 'Student Job Postings',
				icon: 'fingerprint',
				foreground: 'light',
				tint: c.goldenrod,
			},
			{
				type: 'view',
				view: 'StudentOrgsView',
				title: 'Student Orgs',
				icon: 'globe',
				foreground: 'light',
				tint: c.wave,
			},
		],
	],
	[
		'Health, Wellness, & Safety',
		[
			{
				type: 'view',
				view: 'ContactsView',
				title: 'SARN',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			// {icon: null, label: 'SARN', view: 'app.health.sarn'},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'Wellness Center',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'Public Safety',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'Safe Ride',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'Title IX',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'HOPE Center',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'Health Services',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: "Pastors' Office",
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			{
				type: 'view',
				view: 'ContactsView',
				title: 'Counseling Center',
				icon: 'phone',
				foreground: 'light',
				tint: c.crimson,
			},
			// {
			// 	type: 'view',
			// 	view: 'HelpView',
			// 	title: 'Report A Problem',
			// 	icon: 'help',
			// 	foreground: 'light',
			// 	tint: c.lavender,
			// },
			{
				type: 'external-url',
				url: 'https://wp.stolaf.edu/safety-committee/report/',
				view: 'SafetyView',
				title: 'Safety Concerns',
				icon: 'warning',
				foreground: 'dark',
				tint: c.periwinkle,
			},
		],
	],
])

export const allViewNames: Array<string> = []
