import {describe, expect, test} from '@jest/globals'
import moment from 'moment-timezone'
import bundledBusTimes from '../../../../../../docs/bus-times.json'
import {processBusLine} from '../process-bus-line'
import type {UnprocessedBusLine} from '../../types'

// docs/bus-times.json is generated by `bundle-data` from data/bus-times/*.yaml,
// the same file query.ts serves during UI testing. Running the real
// processing over it is what every existing gate skipped: they checked the
// YAML's *shape*, never that the app could actually consume it. Two
// independent bugs hid in that gap -- a consumer dereferencing an absent
// `coordinates` map, and a generator that could silently stop emitting one --
// and the tests below are split to catch each: "does not throw" catches the
// former, and the coverage check below catches the latter even though the
// consumer's own `?.` guard would otherwise let it pass silently.
let lines = (bundledBusTimes as {data: UnprocessedBusLine[]}).data

let now = moment.tz('2026-08-20 12:00', 'America/Chicago')

describe('the bundled bus-times data', () => {
	test('every line processes without throwing', () => {
		for (let line of lines) {
			expect(() => processBusLine(line, now)).not.toThrow()
		}
	})

	test('every schedule has one times row per stop', () => {
		for (let line of lines) {
			let processed = processBusLine(line, now)
			for (let schedule of processed.schedules) {
				// A single-stop schedule -- Oles Go's "Schedule" placeholder -- is an
				// hours range, not a per-stop row, and scripts/validate-bus-schedules.mjs
				// already carves out this same exception for the same reason.
				if (schedule.stops.length <= 1) {
					continue
				}
				for (let row of schedule.times) {
					expect(row.length).toBe(schedule.stops.length)
				}
			}
		}
	})

	test('every parsed departure is either null or a valid Moment', () => {
		for (let line of lines) {
			let processed = processBusLine(line, now)
			for (let schedule of processed.schedules) {
				for (let row of schedule.times) {
					for (let departure of row) {
						if (departure === null) {
							continue
						}
						expect(moment.isMoment(departure)).toBe(true)
						expect(departure.isValid()).toBe(true)
					}
				}
			}
		}
	})

	test('every closure on a generated schedule survives processing unchanged', () => {
		let generatedLines = lines.filter((line) => line.timezone !== undefined)
		let sawAClosure = false

		for (let line of generatedLines) {
			let processed = processBusLine(line, now)

			for (let [i, schedule] of line.schedules.entries()) {
				if (!schedule.closures) {
					continue
				}

				sawAClosure = true
				expect(processed.schedules[i].closures).toEqual(schedule.closures)
				for (let closure of schedule.closures) {
					expect(closure.date).toMatch(/^\d{4}-\d{2}-\d{2}$/u)
					expect(typeof closure.name).toBe('string')
				}
			}
		}

		// The real feed's Blue and Red lines each carry four closures and
		// Express carries one; if the generator ever stopped emitting them,
		// this loop would silently pass by finding nothing to check.
		expect(sawAClosure).toBe(true)
	})

	test('every generated line publishes a coordinate for every stop it serves', () => {
		// The generator always sets `timezone`; a hand-maintained line, like Oles
		// Go, never does -- that is how this picks out "generated" lines. If the
		// generator ever stopped setting `timezone` too, this filter would match
		// nothing and the loop below would pass by doing nothing, so the count is
		// asserted directly rather than trusted.
		let generatedLines = lines.filter((line) => line.timezone !== undefined)

		expect(generatedLines.length).toBeGreaterThanOrEqual(3)

		for (let line of generatedLines) {
			// A route that produced zero schedules would otherwise ship as
			// `schedules: []` -- a file the schema, the validator, and the loop
			// above all accept without complaint. The generator and the schema
			// both reject this now; assert it here too, in the gate that runs
			// against what actually ships.
			expect(line.schedules.length).toBeGreaterThan(0)

			for (let schedule of line.schedules) {
				for (let stopName of schedule.stops) {
					// `coordinates` is keyed by stop name, and a looping route can
					// call at the same stop twice (Blue's Northfield Depot, Express's
					// Carleton and St. Olaf), so its key count is legitimately smaller
					// than `stops.length` -- this checks coverage, not a matching size.
					// (Not `toHaveProperty`: a name like "St. Olaf College" has a dot,
					// which that matcher reads as a nested-path separator.)
					expect(Object.keys(schedule.coordinates ?? {})).toContain(stopName)
					expect(schedule.coordinates?.[stopName]).toEqual([expect.any(Number), expect.any(Number)])
				}
			}
		}
	})
})
