import {describe, expect, test} from '@jest/globals'
import moment from 'moment-timezone'
import bundledBusTimes from '../../../../../../docs/bus-times.json'
import {processBusLine} from '../process-bus-line'
import type {UnprocessedBusLine} from '../../types'

// docs/bus-times.json is generated by `bundle-data` from data/bus-times/*.yaml,
// the same file query.ts serves during UI testing. Running the real
// processing over it is what would have caught the coordinates crash: every
// existing gate checked the YAML's *shape*, none of them checked that the
// app could actually consume it.
let lines = (bundledBusTimes as {data: UnprocessedBusLine[]}).data

let now = moment.tz('2026-08-20 12:00', 'America/Chicago')

describe('the bundled bus-times data', () => {
	test('every line processes without throwing', () => {
		for (let line of lines) {
			expect(() => processBusLine(line, now)).not.toThrow()
		}
	})

	test('every schedule has one times row per stop', () => {
		for (let line of lines) {
			let processed = processBusLine(line, now)
			for (let schedule of processed.schedules) {
				// A single-stop schedule -- Oles Go's "Schedule" placeholder -- is an
				// hours range, not a per-stop row, and scripts/validate-bus-schedules.mjs
				// already carves out this same exception for the same reason.
				if (schedule.stops.length <= 1) {
					continue
				}
				for (let row of schedule.times) {
					expect(row.length).toBe(schedule.stops.length)
				}
			}
		}
	})

	test('every parsed departure is either null or a valid Moment', () => {
		for (let line of lines) {
			let processed = processBusLine(line, now)
			for (let schedule of processed.schedules) {
				for (let row of schedule.times) {
					for (let departure of row) {
						if (departure === null) {
							continue
						}
						expect(moment.isMoment(departure)).toBe(true)
						expect(departure.isValid()).toBe(true)
					}
				}
			}
		}
	})

	test('Oles Go processes, the one line with no timezone and no coordinates', () => {
		let olesGo = lines.find((line) => line.line === 'Oles Go')

		if (!olesGo) {
			throw new Error('expected docs/bus-times.json to carry an "Oles Go" line')
		}

		expect(olesGo.timezone).toBeUndefined()

		let process = () => processBusLine(olesGo, now)

		expect(process).not.toThrow()

		let processed = process()
		for (let schedule of processed.schedules) {
			expect(schedule.coordinates).toEqual({})
			for (let stop of schedule.timetable) {
				expect(stop.coordinates).toBeUndefined()
			}
		}
	})
})
