// flow-typed signature: 2ba3116eed1a18c36da76e43eba5df4f
// flow-typed version: <<STUB>>/@react-native-community/netinfo_v5.9.5/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/netinfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/netinfo' {
  declare module.exports: any;
}
