// flow-typed signature: 94f7abff77ef4bce992ba3b96cad35e3
// flow-typed version: <<STUB>>/@expo/react-native-action-sheet_v3.0.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/react-native-action-sheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/react-native-action-sheet' {
  declare module.exports: any;
}
