// Written by `mise run update-campus-fixtures`; rerecord rather than edit.
import f0 from './GET-api.presence.io-stolaf-v1-events.json'
import f1 from './GET-contacts.json'
import f2 from './GET-dictionary.json'
import f3 from './GET-faqs.json'
import f4 from './GET-food-named-cafe-stav-hall.json'
import f5 from './GET-food-named-menu-stav-hall.json'
import f6 from './GET-map-categories.json'
import f7 from './GET-map-geojson.json'
import f8 from './GET-sources.json'
import f9 from './GET-spaces-directory.json'
import f10 from './GET-spaces-hours.json'
import f11 from './GET-transit-bus.json'
import f12 from './GET-transit-modes.json'
import f13 from './GET-wp.stolaf.edu-calendar-wp-json-tribe-events-v1-events-per_page-50-ends_after-date-starts_before-date.json'
import f14 from './GET-wp.stolaf.edu-calendar-wp-json-tribe-events-v1-events-per_page-50-status-publish-starts_before-date-ends_after-date-page-2.json'
import f15 from './GET-wp.stolaf.edu-calendar-wp-json-tribe-events-v1-events-per_page-50-status-publish-starts_before-date-ends_after-date-page-3.json'
import f16 from './GET-wp.stolaf.edu-calendar-wp-json-tribe-events-v1-events-per_page-50-status-publish-starts_before-date-ends_after-date-page-4.json'
import f17 from './GET-wp.stolaf.edu-wp-json-wp-v2-posts-per_page-10-_embed-true.json'

export default [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17]
