import {client} from '@frogpond/api'
import {queryOptions} from '@tanstack/react-query'
import {isUITesting} from '@frogpond/launch-arguments'
import bundledBusTimes from '../../../../docs/bus-times.json'
import {UnprocessedBusLine} from './types'

export const keys = {
	all: ['transit', 'bus-routes'] as const,
}

async function fetchBusRoutes({signal}: {signal: AbortSignal}): Promise<UnprocessedBusLine[]> {
	// The UI tests run against a frozen clock, so every stop's status follows
	// from the timetable they are handed. Off the server that timetable is
	// whatever the data repo last deployed -- a route St. Olaf reshuffles moves
	// which stop the bus is at, and a test that named one would fail on someone
	// else's schedule. `docs/bus-times.json` is generated by `bundle-data` from
	// `data/bus-times/*.yaml`, so it always matches this checkout.
	if (isUITesting) {
		return (bundledBusTimes as {data: UnprocessedBusLine[]}).data
	}

	let response = await client.get('transit/bus', {signal}).json()
	return (response as {data: UnprocessedBusLine[]}).data
}

export const busRoutesOptions = queryOptions({
	queryKey: keys.all,
	queryFn: fetchBusRoutes,
})

// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const busLineOptions = (lineName: string) =>
	queryOptions({
		queryKey: keys.all,
		queryFn: fetchBusRoutes,
		select: (lines) => lines.find((l) => l.line === lineName),
	})
