import {clientFor} from '@frogpond/api'
import {queryOptions} from '@tanstack/react-query'
import {servesBundledFixtures} from '@frogpond/launch-arguments'
import bundledBusTimes from '../../../../docs/bus-times.json'
import {UnprocessedBusLine} from './types'
import type {CampusId} from '../../../campuses'

export const keys = {
	/** By server, so each campus's lines sit under its own key. */
	forServer: (server: CampusId) => [server, 'transit', 'bus-routes'] as const,
}

async function fetchBusRoutes(
	server: CampusId,
	{signal}: {signal: AbortSignal},
): Promise<UnprocessedBusLine[]> {
	// The UI tests run against a frozen clock, so every stop's status follows
	// from the timetable they are handed. Off the server that timetable is
	// whatever the data repo last deployed -- a route St. Olaf reshuffles moves
	// which stop the bus is at, and a test that named one would fail on someone
	// else's schedule. `docs/bus-times.json` is generated by `bundle-data` from
	// `data/bus-times/*.yaml`, so it always matches this checkout.
	if (servesBundledFixtures) {
		return (bundledBusTimes as {data: UnprocessedBusLine[]}).data
	}

	let response = await clientFor(server).get('transit/bus', {signal}).json()
	return (response as {data: UnprocessedBusLine[]}).data
}

/** The bus lines on `server`, the active campus's transit server. */
// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const busRoutesOptionsFor = (server: CampusId) =>
	queryOptions({
		queryKey: keys.forServer(server),
		queryFn: (context) => fetchBusRoutes(server, context),
	})

// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const busLineOptions = (lineName: string, server: CampusId) =>
	queryOptions({
		queryKey: keys.forServer(server),
		queryFn: (context) => fetchBusRoutes(server, context),
		select: (lines) => lines.find((l) => l.line === lineName),
	})
