// flow-typed signature: 8aa9868f32fc1617e09f742582b6b86c
// flow-typed version: <<STUB>>/@mapbox/react-native-mapbox-gl_v6.1.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/react-native-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/react-native-mapbox-gl' {
  declare module.exports: any;
}
