// flow-typed signature: ea0fa4d49b10c353c428e65195e5b306
// flow-typed version: <<STUB>>/@mapbox/react-native-mapbox-gl_v6.1.2-beta2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/react-native-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/react-native-mapbox-gl' {
  declare module.exports: any;
}
