// @flow

export type RGBTuple = [number, number, number]

export type PosterInfo = {
	url: string,
	filename: string,
	width: number,
	height: number,
}

export type MovieTrailerThumbnail = {
	url: string,
	filename: string,
	width: number,
	height: number,
}

export type MovieTrailer = {
	name: string,
	type: 'Trailer' | 'Teaser' | 'Featurette' | 'Clip',
	url: string,
	lang: string,
	thumbnails: Array<MovieTrailerThumbnail>,
	colors: {
		dominant: RGBTuple,
		palette: Array<RGBTuple>,
	},
}

export type MovieShowing = {time: string, location: string}

export type GroupedShowing = {
	// generated by groupShowings
	key: string,
	date: string,
	month: string,
	location: string,
	times: Array<string>,
}

export type MovieRating = {Source: string, Value: string}

export type MovieInfo = {
	Title: string,
	Year: string,
	Rated: string,
	Released: string,
	ReleaseDate: string,
	Runtime: string,
	Genre: string,
	Genres: Array<string>,
	Director: string,
	Writer: string,
	Actors: string,
	Plot: string,
	Language: string,
	Country: string,
	Awards: string,
	Ratings: Array<MovieRating>,
	Type: string,
	DVD: string,
	BoxOffice: string,
	Production: string,
	imdbID: string,
	Website: string,
}

export type Movie = {
	root: string,
	info: MovieInfo,
	showings: Array<MovieShowing>,
	trailers: Array<MovieTrailer>,
	poster: {
		sizes: Array<PosterInfo>,
		colors: {
			dominant: RGBTuple,
			palette: Array<RGBTuple>,
		},
	}
}
