require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'AllAboutOlaf' do
	inhibit_all_warnings!

	config = use_native_modules!

	use_react_native!(
		:path => config[:reactNativePath],
		# to enable hermes on iOS, change `false` to `true` and then install pods
		:hermes_enabled => false
	)

	target 'AllAboutOlafUITests' do
		inherit! :complete
		# Pods for testing
	end

	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable the next line.
	# use_flipper!()
	#
	# In order to build/run without duplicate symbols errors (Flipper-Folly
	# and RCT-Folly) we can downgrade Flipper-DoubleConversion as a stopgap.
	use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" }) 

	post_install do |installer|
		react_native_post_install(installer)
		__apply_Xcode_12_5_M1_post_install_workaround(installer)
	end
end
