require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Load react_native_pods.rb from the app's local node_modules directory.
# This assumes node_modules is located at ../node_modules relative to ios/.
require '../node_modules/react-native/scripts/react_native_pods.rb'

# expo-modules-autolinking patches UserProjectIntegrator#integrate_user_targets
# so that it calls integrate_targets_in_project for every CocoaPods target whose
# TargetDefinition has an autolinking_manager set. Because AllAboutOlafUITests is
# nested inside AllAboutOlaf, it inherits AllAboutOlaf's autolinking_manager via
# TargetDefinition#autolinking_manager's parent-traversal logic. This causes expo
# to add ExpoModulesProvider.swift (source file + "[Expo] Configure project" run
# script) to the UITests native target, which then fails to link because the expo
# module static libraries aren't linked into UITests.
#
# Fix: prepend a module override that returns nil for AllAboutOlafUITests so that
# expo's integrate_targets_in_project skips it entirely.
module ExpoUITestsAutolinkingFix
  def autolinking_manager
    return nil if name == 'AllAboutOlafUITests'
    super
  end
end
Pod::Podfile::TargetDefinition.prepend(ExpoUITestsAutolinkingFix)

# Opt out of the New Architecture (Fabric/TurboModules/Bridgeless).
# The Old Architecture is fully supported through RN 0.76.
# See: https://github.com/StoDevX/AAO-React-Native/issues/7453
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AllAboutOlaf' do
	use_expo_modules!
	inhibit_all_warnings!

	config = use_native_modules!

	use_react_native!(
		:path => config[:reactNativePath],
		# An absolute path to your application root.
		:app_path => "#{Pod::Config.instance.installation_root}/.."
	)

	target 'AllAboutOlafUITests' do
		inherit! :search_paths
	end

	post_install do |installer|
		ccache_enabled = ENV['USE_CCACHE'] == '1'

		# https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
		react_native_post_install(
			installer,
			config[:reactNativePath],
			:mac_catalyst_enabled => false,
			:ccache_enabled => ccache_enabled
		)

		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				# cocoapods defaults to not stripping the frameworks it creates
				# issue for cocoapods is https://github.com/CocoaPods/CocoaPods/issues/10277
				config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES'

				# ccache replaces CC with a wrapper script that Xcode 16+'s
				# explicit modules feature doesn't recognize
				if ccache_enabled
					config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
				end
			end
		end

		system('cd .. && scripts/apply-patches.sh')
	end
end
