name: AllAboutOlaf
options:
  bundleIdPrefix: ""
  deploymentTarget:
    iOS: "17.2"
  xcodeVersion: "1300"
  developmentLanguage: en
  defaultConfig: Release

configs:
  Debug: debug
  Release: release

settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: "NO"
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: "YES"
    CLANG_CXX_LANGUAGE_STANDARD: "c++17"
    CLANG_CXX_LIBRARY: "libc++"
    CLANG_ENABLE_MODULES: "YES"
    CLANG_ENABLE_OBJC_ARC: "YES"
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
    CLANG_WARN_BOOL_CONVERSION: "YES"
    CLANG_WARN_COMMA: "YES"
    CLANG_WARN_CONSTANT_CONVERSION: "YES"
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_EMPTY_BODY: "YES"
    CLANG_WARN_ENUM_CONVERSION: "YES"
    CLANG_WARN_INFINITE_RECURSION: "YES"
    CLANG_WARN_INT_CONVERSION: "YES"
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
    CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: "YES"
    CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
    CLANG_WARN_STRICT_PROTOTYPES: "YES"
    CLANG_WARN_SUSPICIOUS_MOVE: "YES"
    CLANG_WARN_UNREACHABLE_CODE: "YES"
    CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
    CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Developer"
    CURRENT_PROJECT_VERSION: 16
    ENABLE_STRICT_OBJC_MSGSEND: "YES"
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: i386
    GCC_C_LANGUAGE_STANDARD: gnu99
    GCC_NO_COMMON_BLOCKS: "YES"
    GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: "YES"
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: "YES"
    GCC_WARN_UNUSED_VARIABLE: "YES"
    HEADER_SEARCH_PATHS: "$(inherited)"
    IPHONEOS_DEPLOYMENT_TARGET: "17.2"
    OTHER_CFLAGS: "$(inherited)"
    OTHER_CPLUSPLUSFLAGS: "$(inherited)"
    REACT_NATIVE_PATH: "${PODS_ROOT}/../../node_modules/react-native"
    SDKROOT: iphoneos
    SWIFT_VERSION: "5.0"
    VERSIONING_SYSTEM: "apple-generic"
  configs:
    Debug:
      COPY_PHASE_STRIP: "NO"
      ENABLE_TESTABILITY: "YES"
      GCC_DYNAMIC_NO_PIC: "NO"
      GCC_OPTIMIZATION_LEVEL: "0"
      GCC_PREPROCESSOR_DEFINITIONS:
        - "DEBUG=1"
        - "$(inherited)"
      GCC_SYMBOLS_PRIVATE_EXTERN: "NO"
      MTL_ENABLE_DEBUG_INFO: "YES"
      ONLY_ACTIVE_ARCH: "YES"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      COPY_PHASE_STRIP: "YES"
      ENABLE_NS_ASSERTIONS: "NO"
      MTL_ENABLE_DEBUG_INFO: "NO"
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      VALIDATE_PRODUCT: "YES"

targets:
  AllAboutOlaf:
    type: application
    platform: iOS
    productName: AllAboutOlaf
    sources:
      - path: AllAboutOlaf
        excludes:
          - Info.plist
          - "*.entitlements"
    resources:
      - path: PrivacyInfo.xcprivacy
      - path: ../images/icons/windmill@2x.png
      - path: ../images/icons/windmill@3x.png
      - path: ../images/icons/windmill@2x~iPad.png
      - path: ../images/icons/windmill@3x~iPad.png
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CLANG_ENABLE_MODULES: "YES"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Developer"
        CODE_SIGN_STYLE: Manual
        DEAD_CODE_STRIPPING: "YES"
        DEPLOYMENT_POSTPROCESSING: "YES"
        DEVELOPMENT_TEAM: ""
        DEVELOPMENT_TEAM[sdk=iphoneos*]: TMK6S7TPX2
        HEADER_SEARCH_PATHS: "$(inherited)"
        INFOPLIST_FILE: AllAboutOlaf/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-ObjC"
          - "-lc++"
        PRODUCT_BUNDLE_IDENTIFIER: NFMTHAZVS9.com.drewvolz.stolaf
        PROVISIONING_PROFILE_SPECIFIER: ""
        STRIPFLAGS: "-rSTx"
        SWIFT_OBJC_BRIDGING_HEADER: AllAboutOlafUITests/AllAboutOlaf-Bridging-Header.h
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Developer"
          ENABLE_TESTABILITY: "YES"
          PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match Development NFMTHAZVS9.com.drewvolz.stolaf"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match AppStore NFMTHAZVS9.com.drewvolz.stolaf"
    entitlements:
      path: AllAboutOlaf/AllAboutOlaf.entitlements
    postBuildScripts:
      - name: "Bundle React Native code and images"
        script: |
          export NODE_BINARY=node
          ../node_modules/react-native/scripts/react-native-xcode.sh
        basedOnDependencyAnalysis: false

  AllAboutOlafUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: AllAboutOlafUITests
        excludes:
          - Info.plist
      - path: fastlane/SnapshotHelper.swift
    settings:
      base:
        CLANG_ANALYZER_NONNULL: "YES"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        CLANG_WARN_SUSPICIOUS_MOVES: "YES"
        INFOPLIST_FILE: AllAboutOlafUITests/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
        LIBRARY_SEARCH_PATHS: "$(SDKROOT)/usr/lib/swift$(inherited)"
        PRODUCT_BUNDLE_IDENTIFIER: "hawkrives.All-About-Olaf-UI-Tests"
        PRODUCT_NAME: "$(TARGET_NAME)"
        TEST_TARGET_NAME: AllAboutOlaf
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          COPY_PHASE_STRIP: "NO"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    dependencies:
      - target: AllAboutOlaf

schemes:
  AllAboutOlaf:
    build:
      parallelizeBuild: false
      targets:
        AllAboutOlaf:
          testing: true
          running: true
          profiling: true
          archiving: true
          analyzing: true
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AllAboutOlafUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: true
