// @flow
export const buildingImages = {
  'alumni-hall': require('./buildinghours/w1440/alumni-hall.jpg'),
  'boe': require('./buildinghours/w1440/boe.jpg'),
  'bookstore': require('./buildinghours/w1440/bookstore.jpg'),
  'buntrock': require('./buildinghours/w1440/buntrock.jpg'),
  'cage': require('./buildinghours/w1440/cage.jpg'),
  'center-for-arts-and-dance': require('./buildinghours/w1440/dittmann.jpg'),
  'christiansen': require('./buildinghours/w1440/christiansen.jpg'),
  'convenience': require('./buildinghours/w1440/convenience.jpg'),
  'disco': require('./buildinghours/w1440/disco.jpg'),
  'hall-of-music': require('./buildinghours/w1440/hall-of-music.jpg'),
  'halvorson': require('./buildinghours/w1440/halvorson.jpg'),
  'old-main': require('./buildinghours/w1440/old-main.jpg'),
  'pause-kitchen': require('./buildinghours/w1440/pause-kitchen.jpg'),
  'print': require('./buildinghours/w1440/print.jpg'),
  'post-office': require('./buildinghours/w1440/post-office.jpg'),
  'regents-hall': require('./buildinghours/w1440/regents-hall.jpg'),
  'regents-math': require('./buildinghours/w1440/regents-math.jpg'),
  'rolvaag-library': require('./buildinghours/w1440/rolvaag-library.jpg'),
  'skifter-studioa': require('./buildinghours/w1440/skifter-studioa.jpg'),
  'skoglund': require('./buildinghours/w1440/skoglund.jpg'),
  'stav': require('./buildinghours/w1440/stav.jpg'),
  'theater': require('./buildinghours/w1440/theater.jpg'),
  'tom-porter': require('./buildinghours/w1440/tom-porter.jpg'),
  'tomson': require('./buildinghours/w1440/tomson.jpg'),
  'wellness': require('./buildinghours/w1440/wellness.jpg'),
}
