// @flow
export const buildingImages = {
  'alumni-hall': require('./buildinghours/optimized/alumni-hall.jpg'),
  'boe': require('./buildinghours/optimized/boe.jpg'),
  'bookstore': require('./buildinghours/optimized/bookstore.jpg'),
  'buntrock': require('./buildinghours/optimized/buntrock.jpg'),
  'cage': require('./buildinghours/optimized/cage.jpg'),
  'center-for-arts-and-dance': require('./buildinghours/optimized/center-for-arts-and-dance.jpg'),
  'christiansen': require('./buildinghours/optimized/christiansen.jpg'),
  'convenience': require('./buildinghours/optimized/convenience.jpg'),
  'disco': require('./buildinghours/optimized/disco.jpg'),
  'hall-of-music': require('./buildinghours/optimized/hall-of-music.jpg'),
  'halvorson': require('./buildinghours/optimized/halvorson.jpg'),
  'old-main': require('./buildinghours/optimized/old-main.jpg'),
  'pause-kitchen': require('./buildinghours/optimized/pause-kitchen.jpg'),
  'print': require('./buildinghours/optimized/print.jpg'),
  'post-office': require('./buildinghours/optimized/post-office.jpg'),
  'regents-hall': require('./buildinghours/optimized/regents-hall.jpg'),
  'regents-math': require('./buildinghours/optimized/regents-math.jpg'),
  'rolvaag-library': require('./buildinghours/optimized/rolvaag-library.jpg'),
  'skifter-studioa': require('./buildinghours/optimized/skifter-studioa.jpg'),
  'skoglund': require('./buildinghours/optimized/skoglund.jpg'),
  'stav': require('./buildinghours/optimized/stav.jpg'),
  'theater': require('./buildinghours/optimized/theater.jpg'),
  'tom-porter': require('./buildinghours/optimized/tom-porter.jpg'),
  'tomson': require('./buildinghours/optimized/tomson.jpg'),
  'wellness': require('./buildinghours/optimized/wellness.jpg'),
}
