# `fastlane` reports which actions are used No personal data is recorded.
# Learn more at https://github.com/fastlane/enhancer

# Customise this file! Documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs

# You should change your syntax highlighting to Ruby.
# All lines starting with a # are comments.

# To automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this if you use features of a newer version:
fastlane_version "1.108.0"

hockeyapp_api_token = ENV["HOCKEYAPP_TOKEN"]


desc "Adds any unregistered devices to the provisioning profile"
lane :register do
  id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  new_devices = get_unprovisioned_devices_from_hockey(app_bundle_id: id)
  register_devices(devices: new_devices)
  match(force: true)
end


platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Activate the rogue signing team"
  private_lane :go_rogue do
    sh("cd .. && ruby scripts/go-rogue.rb")
  end

  desc "In case match needs to be updated - probably never needs to be run"
  lane :update_match do
    match(readonly: false)
  end

  desc "Do CI-system keychain setup"
  lane :ci_keychains do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      timeout: 3600,
    )

    match(readonly: true)

    sh("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["MATCH_KEYCHAIN_PASSWORD"]} #{ENV["MATCH_KEYCHAIN_NAME"]}")
  end

  desc "Provisions the profiles; bumps the build number; builds the app"
  lane :build do
    # Set up code signing correctly
    # (more information: https://codesigning.guide)
    match(readonly: true)

    go_rogue

    increment_build_number(
      build_number: get_version(platform: 'iOS'),
      xcodeproj: "./ios/AllAboutOlaf.xcodeproj",
    )

    # Build the app
    gym(sdk: "iphoneos10.1")
  end

  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
    build

    hockey(
      api_token: hockeyapp_api_token,
      ipa: "./ios/build/AllAboutOlaf.ipa",
      commit_sha: ENV["TRAVIS_COMMIT"],
      notes: make_changelog,
    )
  end
end


platform :android do
  dir = "./android"

  desc "Makes a build"
  lane :build do
    increment_version_code(
      version_code: get_version(platform: 'Android'),
      app_folder_name: dir,
    )

    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: dir,
      print_command: true,
      print_command_output: true,
    )
  end

  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
    build

    # Upload to HockeyApp
    hockey(
      api_token: hockeyapp_api_token,
      apk: "./android/app/build/outputs/apk/app-release-unsigned.apk",
      commit_sha: ENV["TRAVIS_COMMIT"],
      notes: make_changelog,
    )
  end
end


# Below here are the custom helpers we've defined

desc "Makes a changelog from the git commits that were committed today"
private_lane :make_changelog do
  sh("git log --since yesterday --pretty='%an, %aD (%h)%n> %s%n' | sed 's/^/    /'")
end


desc "Get the hockeyapp version"
private_lane :get_hockeyapp_version do |options|
  latest_hockeyapp_version_number(
    api_token: hockeyapp_api_token,
    app_name: "All About Olaf",
    platform: options[:platform],
  )
end


desc "Gets the version, either from Travis or from Hockey"
private_lane :get_version do |options|
  ENV["TRAVIS_BUILD_NUMBER"] or get_hockeyapp_version(platform: options[:platform]) + 1
end

