# `fastlane` reports which actions are used No personal data is recorded.
# Learn more at https://github.com/fastlane/enhancer

# Customise this file! Documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs

# You should change your syntax highlighting to Ruby.
# All lines starting with a # are comments.

# To automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this if you use features of a newer version:
fastlane_version "1.108.0"


desc "Makes a changelog from the git commits that were committed today"
private_lane :make_changelog do
  sh("git log --since yesterday --pretty='%an, %aD (%h)%n> %s%n' | sed 's/^/    /'")
end


platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Provisions the profiles; bumps the build number; builds the app"
  private_lane :build do
    # Set up code signing correctly
    # (more information: https://codesigning.guide)
    match(readonly: true)

    increment_build_number(
      build_number: ENV["TRAVIS_BUILD_NUMBER"] || ENV["BUILD"],
      xcodeproj: "ios/AllAboutOlaf.xcodeproj",
    )

    # Build the app
    gym(sdk: "iphoneos10.1")
  end

  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
    build

    hockey(
      api_token: "28aa2d30407042b49855e871db8a56ed",
      ipa: "./ios/build/AllAboutOlaf.ipa",
      commit_sha: ENV["TRAVIS_COMMIT"],
      notes: make_changelog,
    )
  end
end


platform :android do
  before_all do
  end

  desc "Makes a build"
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android",
      print_command: true,
      print_command_output: true,
    )
  end

  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
    build

    # Upload to HockeyApp
    hockey(
      api_token: "28aa2d30407042b49855e871db8a56ed",
      apk: "./android/app/build/outputs/apk/app-release-unsigned.apk",
      commit_sha: ENV["TRAVIS_COMMIT"],
      notes: make_changelog,
    )
  end
end
