# A list of devices you want to take the screenshots from
devices([
  "iPhone 7 Plus",
  "iPhone 6",
  "iPhone 5s",
  "iPhone 4s",
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme "AllAboutOlaf"
workspace "ios/AllAboutOlaf.xcworkspace"

# Where should the resulting screenshots be stored?
output_directory "fastlane/screenshots"

# uncomment to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots true

# For more information about all available options run
# snapshot --help
