import {carletonClient, stolafClient} from '@frogpond/api'
import {queryOptions} from '@tanstack/react-query'
import {isUITesting} from '@frogpond/launch-arguments'
import contactInfoData from '../../../docs/contact-info.json'
import {ContactType} from './types'
import type {Campus} from '../campus/store'

/// Named apart from this feature's `keys`, in query.ts, which addresses the
/// St. Olaf directory search rather than these.
export const contactKeys = {
	all: ['contacts'] as const,
	/** St. Olaf's keeps the key it always had; Carleton's sits under the campus. */
	forCampus: (campus: Campus): readonly string[] =>
		campus === 'carleton' ? (['carleton', 'contacts'] as const) : contactKeys.all,
}

async function fetchContacts(campus: Campus, {signal}: {signal: AbortSignal}) {
	// The UI tests read contacts out of the bundle rather than off the server,
	// because the two move independently: `data/contact-info/*.yaml` reaches
	// production by a deploy of its own, so a test asserting on a title, an
	// icon or a gradient would be asserting on whatever happens to be deployed
	// at the time. Worse, a change to that data cannot go green until it has
	// shipped, and it cannot ship until it is green. `docs/contact-info.json`
	// is generated by `bundle-data` from those same files, so it always
	// matches the code in the same checkout.
	if (isUITesting) {
		return (contactInfoData as {data: ContactType[]}).data
	}

	let api = campus === 'carleton' ? carletonClient : stolafClient
	let response = await api.get('contacts', {signal}).json()
	// The server sends whatever the data repo deployed, so this is an
	// assertion, not a check. `icon` in particular claims to be an SFSymbol on
	// no evidence; the tile falls back only when it is missing -- a wrong name
	// draws nothing, since SwiftUI's Image(systemName:) does not validate it.
	return (response as {data: ContactType[]}).data
}

// Contacts are hand-curated reference data (see data/contact-info/*.yaml) that
// changes on the order of weeks, not minutes. Without a staleTime, React
// Query's default (0) marks the cache stale immediately, so mounting the
// detail screen -- a second observer on the same queryKey -- triggers a
// background refetch on top of the one the grid already ran. A few minutes of
// staleness avoids that redundant request while still catching same-session
// edits.
const staleTime = 1000 * 60 * 5 // 5 minutes

/** `campus`'s important contacts. */
// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const contactsOptionsFor = (campus: Campus) =>
	queryOptions({
		queryKey: contactKeys.forCampus(campus),
		queryFn: (context) => fetchContacts(campus, context),
		staleTime,
	})

export const contactsOptions = contactsOptionsFor('stolaf')

// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const contactByTitleOptions = (title: string, campus: Campus = 'stolaf') =>
	queryOptions({
		queryKey: contactKeys.forCampus(campus),
		queryFn: (context) => fetchContacts(campus, context),
		select: (contacts) => contacts.find((c) => c.title === title),
		staleTime,
	})
