import {client} from '@frogpond/api'
import {queryOptions} from '@tanstack/react-query'
import {isUITesting} from '@frogpond/launch-arguments'
import contactInfoData from '../../../docs/contact-info.json'
import {ContactType} from './types'

/// Named apart from this feature's `keys`, in query.ts, which addresses the
/// St. Olaf directory search rather than these.
export const contactKeys = {
	all: ['contacts'] as const,
}

async function fetchContacts({signal}: {signal: AbortSignal}) {
	// A UI test that asserts on a contact's title can't depend on the live
	// server: this branch's data (renamed titles, `icon`, `gradient`) only
	// reaches production once this branch merges, and the merge itself
	// requires a green suite -- fetching live here would make the suite
	// unmergeable by construction. `docs/contact-info.json` is generated by
	// `bundle-data` from the same `data/contact-info/*.yaml` this branch
	// edits, so it always matches what the app's own code expects.
	if (isUITesting) {
		return (contactInfoData as {data: ContactType[]}).data
	}

	let response = await client.get('contacts', {signal}).json()
	// The server sends whatever the data repo deployed, so this is an
	// assertion, not a check. `icon` in particular claims to be an SFSymbol on
	// no evidence; the tile draws a fallback when it is wrong.
	return (response as {data: ContactType[]}).data
}

// Contacts are hand-curated reference data (see data/contact-info/*.yaml) that
// changes on the order of weeks, not minutes. Without a staleTime, React
// Query's default (0) marks the cache stale immediately, so mounting the
// detail screen -- a second observer on the same queryKey -- triggers a
// background refetch on top of the one the grid already ran. A few minutes of
// staleness avoids that redundant request while still catching same-session
// edits.
const staleTime = 1000 * 60 * 5 // 5 minutes

export const contactsOptions = queryOptions({
	queryKey: contactKeys.all,
	queryFn: fetchContacts,
	staleTime,
})

// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const contactByTitleOptions = (title: string) =>
	queryOptions({
		queryKey: contactKeys.all,
		queryFn: fetchContacts,
		select: (contacts) => contacts.find((c) => c.title === title),
		staleTime,
	})
