#!/usr/bin/env node

// Lists every route in app/ as uitests/Chaos/ChaosRoutes.swift, so the chaos
// monkey can open any screen by URL, including ones no tile leads to.

import {readdirSync, writeFileSync} from 'node:fs'
import {fileURLToPath} from 'node:url'

const APP_DIR = new URL('../app/', import.meta.url)
const OUTPUT = new URL('../uitests/Chaos/ChaosRoutes.swift', import.meta.url)

/** Routes the monkey should not open: the canary's own crash. */
const SKIPPED = new Set(['chaos-crash'])

/** Every file under app/, relative to it. */
export function appRouteFiles() {
	return readdirSync(fileURLToPath(APP_DIR), {recursive: true})
}

/**
 * The routes `paths` define. Layouts, `+` special files and dotfiles define
 * none; `index` is its directory; a `(group)` segment is not part of the URL.
 */
export function routesIn(paths) {
	let routes = new Set()
	for (let path of paths) {
		let match = /^(.*)\.tsx?$/u.exec(path)
		if (!match) continue
		let segments = match[1].split('/')
		let last = segments.at(-1)
		if (last === '_layout' || last.startsWith('+') || last.startsWith('.')) continue
		if (last === 'index') segments.pop()
		let route = segments.filter((s) => !/^\(.*\)$/u.test(s)).join('/')
		if (SKIPPED.has(route)) continue
		routes.add(route)
	}
	return [...routes].sort(compareStrings)
}

/** `routes` as the Swift table the monkey reads. */
export function renderSwift(routes) {
	return [
		'// Generated by scripts/chaos-routes.mjs from app/. Run `mise run chaos-routes` after adding a route.',
		'',
		'/// Every route in app/, for the chaos monkey to open by URL.',
		'enum ChaosRoutes {',
		'\tstatic let all = [',
		...routes.map((route) => `\t\t${JSON.stringify(route)},`),
		'\t]',
		'}',
		'',
	].join('\n')
}

/** Sort strings lexicographically. */
function compareStrings(a, b) {
	return a.localeCompare(b)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	writeFileSync(OUTPUT, renderSwift(routesIn(appRouteFiles())))
}
