import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {test} from 'node:test'

import {appRouteFiles, renderSwift, routesIn} from './chaos-routes.mjs'

test('turns route files into routes', () => {
	assert.deepEqual(
		routesIn([
			'_layout.tsx',
			'index.tsx',
			'athletics.tsx',
			'calendar/index.tsx',
			'calendar/event/_layout.tsx',
			'calendar/event/index.tsx',
			'directory/[index].tsx',
			'settings/debug/[...keyPath].tsx',
			'(tabs)/news.tsx',
			'+not-found.tsx',
			'chaos-crash.tsx',
			'.DS_Store',
		]),
		[
			'',
			'athletics',
			'calendar',
			'calendar/event',
			'directory/[index]',
			'news',
			'settings/debug/[...keyPath]',
		],
	)
})

test('renders a Swift table', () => {
	assert.equal(
		renderSwift(['', 'athletics']),
		[
			'// Generated by scripts/chaos-routes.mjs from app/. Run `mise run chaos-routes` after adding a route.',
			'',
			'/// Every route in app/, for the chaos monkey to open by URL.',
			'enum ChaosRoutes {',
			'\tstatic let all = [',
			'\t\t"",',
			'\t\t"athletics",',
			'\t]',
			'}',
			'',
		].join('\n'),
	)
})

test('the checked-in table is current', () => {
	let checkedIn = readFileSync(
		new URL('../uitests/Chaos/ChaosRoutes.swift', import.meta.url),
		'utf8',
	)
	assert.equal(checkedIn, renderSwift(routesIn(appRouteFiles())), 'run mise run chaos-routes')
})
