import {clientFor} from '@frogpond/api'
import {servesBundledFixtures} from '@frogpond/launch-arguments'
import {queryOptions} from '@tanstack/react-query'

import bundledModes from '../../../../docs/transportation.json'
import {OtherModeType} from '../types'
import {groupBy} from '@frogpond/collections'
import type {CampusId} from '../../../campuses'

export const keys = {
	/** By server, so each campus's modes sit under its own key. */
	forServer: (server: CampusId) => [server, 'transit', 'modes'] as const,
}

// The UI tests naming no campus assert on the section headings these categories become, so they
// have to come from this checkout rather than from whatever the server is
// serving -- a category renamed here would otherwise pass CI and fail once the
// data deploys. `docs/transportation.json` is generated by `bundle-data` from
// `data/transportation/*.yaml`, so it always matches.
async function fetchOtherModes(
	server: CampusId,
	{signal}: {signal: AbortSignal},
): Promise<OtherModeType[]> {
	if (servesBundledFixtures) {
		return (bundledModes as {data: OtherModeType[]}).data
	}

	let response = await clientFor(server).get('transit/modes', {signal}).json()
	return (response as {data: OtherModeType[]}).data
}

/**
 * The modes as the screen's sections, in the order the server listed their
 * categories.
 *
 * A mode with no category gets a section with no title rather than one titled
 * `''`: the row it holds points at the college's own transportation page, which
 * is a pointer rather than a category and reads better without a heading. The
 * `undefined` passes straight to `Section`, which draws no header for it.
 */
export function groupOtherModes(
	modes: OtherModeType[],
): Array<{title: string | undefined; data: OtherModeType[]}> {
	let grouped = groupBy(modes, (m) => m.category)
	return Object.entries(grouped).map(([key, value]) => ({title: key || undefined, data: value}))
}

/** The other ways to travel on `server`, the active campus's transit server, as the screen's sections. */
// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const otherModesGroupedOptionsFor = (server: CampusId) =>
	queryOptions({
		queryKey: keys.forServer(server),
		queryFn: (context) => fetchOtherModes(server, context),
		select: groupOtherModes,
	})
