import {client} from '@frogpond/api'
import {isUITesting} from '@frogpond/launch-arguments'
import {queryOptions} from '@tanstack/react-query'
import {groupBy, toPairs} from 'lodash'

import bundledModes from '../../../../docs/transportation.json'
import {OtherModeType} from '../types'

export const keys = {
	all: ['transit', 'modes'] as const,
}

// The UI tests assert on the section headings these categories become, so they
// have to come from this checkout rather than from whatever the server is
// serving -- a category renamed here would otherwise pass CI and fail once the
// data deploys. `docs/transportation.json` is generated by `bundle-data` from
// `data/transportation/*.yaml`, so it always matches.
async function fetchOtherModes({signal}: {signal: AbortSignal}): Promise<OtherModeType[]> {
	if (isUITesting) {
		return (bundledModes as {data: OtherModeType[]}).data
	}

	let response = await client.get('transit/modes', {signal}).json()
	return (response as {data: OtherModeType[]}).data
}

export const otherModesOptions = queryOptions({
	queryKey: keys.all,
	queryFn: fetchOtherModes,
})

/**
 * The modes as the screen's sections, in the order the server listed their
 * categories.
 *
 * A mode with no category gets a section with no title rather than one titled
 * `''`: the row it holds points at the college's own transportation page, which
 * is a pointer rather than a category and reads better without a heading. The
 * `undefined` passes straight to `Section`, which draws no header for it.
 */
export function groupOtherModes(
	modes: OtherModeType[],
): Array<{title: string | undefined; data: OtherModeType[]}> {
	let grouped = groupBy(modes, (m) => m.category)
	return toPairs(grouped).map(([key, value]) => ({title: key || undefined, data: value}))
}

export const otherModesGroupedOptions = queryOptions({
	queryKey: keys.all,
	queryFn: fetchOtherModes,
	select: groupOtherModes,
})
