import {clientFor} from '@frogpond/api'
import {servesBundledFixtures} from '@frogpond/launch-arguments'
import {queryOptions} from '@tanstack/react-query'

import bundledModes from '../../../../docs/transportation.json'
import {OtherModeType} from '../types'
import {groupBy} from '@frogpond/collections'
import {campusIdOfLegacy, type Campus} from '../../campus/store'

export const keys = {
	all: ['transit', 'modes'] as const,
	/** St. Olaf's keeps the key it always had; Carleton's sits under the campus. */
	forCampus: (campus: Campus): readonly string[] =>
		campus === 'carleton' ? (['carleton', 'transit', 'modes'] as const) : keys.all,
}

// The UI tests naming no campus assert on the section headings these categories become, so they
// have to come from this checkout rather than from whatever the server is
// serving -- a category renamed here would otherwise pass CI and fail once the
// data deploys. `docs/transportation.json` is generated by `bundle-data` from
// `data/transportation/*.yaml`, so it always matches.
async function fetchOtherModes(
	campus: Campus,
	{signal}: {signal: AbortSignal},
): Promise<OtherModeType[]> {
	if (servesBundledFixtures) {
		return (bundledModes as {data: OtherModeType[]}).data
	}

	let api = clientFor(campusIdOfLegacy(campus))
	let response = await api.get('transit/modes', {signal}).json()
	return (response as {data: OtherModeType[]}).data
}

export const otherModesOptions = queryOptions({
	queryKey: keys.all,
	queryFn: (context) => fetchOtherModes('stolaf', context),
})

/**
 * The modes as the screen's sections, in the order the server listed their
 * categories.
 *
 * A mode with no category gets a section with no title rather than one titled
 * `''`: the row it holds points at the college's own transportation page, which
 * is a pointer rather than a category and reads better without a heading. The
 * `undefined` passes straight to `Section`, which draws no header for it.
 */
export function groupOtherModes(
	modes: OtherModeType[],
): Array<{title: string | undefined; data: OtherModeType[]}> {
	let grouped = groupBy(modes, (m) => m.category)
	return Object.entries(grouped).map(([key, value]) => ({title: key || undefined, data: value}))
}

/** `campus`'s other ways to travel, as the screen's sections. */
// oxlint-disable-next-line typescript/explicit-module-boundary-types
export const otherModesGroupedOptionsFor = (campus: Campus) =>
	queryOptions({
		queryKey: keys.forCampus(campus),
		queryFn: (context) => fetchOtherModes(campus, context),
		select: groupOtherModes,
	})

export const otherModesGroupedOptions = otherModesGroupedOptionsFor('stolaf')
