// flow-typed signature: b975d0d4baca2f1ac792537dd75e629c
// flow-typed version: <<STUB>>/@hawkrives/react-native-alternate-icons_v0.4.7/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hawkrives/react-native-alternate-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hawkrives/react-native-alternate-icons' {
  declare module.exports: any;
}
