// flow-typed signature: a32a459a31b0f0c148f352bd654092ba
// flow-typed version: <<STUB>>/@hawkrives/react-native-alternate-icons_v0.6.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hawkrives/react-native-alternate-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hawkrives/react-native-alternate-icons' {
  declare module.exports: any;
}
