name: Analyze and Build

on: push

jobs:
  js:
    name: JavaScript Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: {node-version: ^12.0}
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn run bundle-data
      - run: yarn run pretty
      - run: yarn run flow check
      - run: yarn run lint
      - name: Run tests
        run: yarn run test --coverage
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

  bundle-android:
    name: Test Android Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: {node-version: ^12.0}
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn run bundle-data
      - run: yarn run --silent bundle:android

  bundle-ios:
    name: Test iOS Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: {node-version: ^12.0}
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn run bundle-data
      - run: yarn run --silent bundle:ios

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: {node-version: ^12.0}
      - uses: actions/setup-ruby@master
        with: {ruby-version: ^2.6}
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: gem install bundler && bundle check || bundle install --frozen --path vendor/bundle
      - run: cd android && ./gradlew androidDependencies --console=plain
      - run: echo 'org.gradle.workers.max=2' >> ./android/gradle.properties
      - run: bundle exec fastlane android ci-run
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
          ONESIGNAL_KEY: ${{ secrets.ONESIGNAL_KEY }}
          GIT_COMMIT_DESC: $(git log --format=oneline -n 1 $GITHUB_SHA)
          FASTLANE_SKIP_UPDATE_CHECK: '1'
          FASTLANE_DISABLE_ANIMATION: '1'
          SENTRY_PROPERTIES: '../android/sentry.properties'
          GITHUB_KEYS_REPOSITORY_TOKEN: ${{ secrets.GITHUB_KEYS_REPOSITORY_TOKEN }}

  ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-node@master
        with: {node-version: ^12.0}
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: gem install bundler && bundle check || bundle install --frozen --path vendor/bundle
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: sudo xcode-select -switch /Applications/Xcode_10.3.app
      - run: bundle exec fastlane ios ci-run
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
          ONESIGNAL_KEY: ${{ secrets.ONESIGNAL_KEY }}
          GIT_COMMIT_DESC: $(git log --format=oneline -n 1 $GITHUB_SHA)
          FASTLANE_SKIP_UPDATE_CHECK: '1'
          FASTLANE_DISABLE_ANIMATION: '1'
          SENTRY_PROPERTIES: '../ios/sentry.properties'
          GITHUB_KEYS_REPOSITORY_TOKEN: ${{ secrets.GITHUB_KEYS_REPOSITORY_TOKEN }}
      - run: yarn detox build e2e --configuration ios.sim.release | xcpretty
      - run: yarn detox test e2e --configuration ios.sim.release --cleanup
