name: Analyze and build the source

on: push

jobs:
  js:
    name: js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@master
      with:
        version: ^12.0
    - uses: actions/checkout@master
    - run: yarn install
    - run: yarn run bundle-data
    - run: yarn run pretty
    - run: yarn run flow check
    - run: yarn run lint
    - name: Run tests
      run: yarn run test --coverage
