name: Analyze and Build

on: push

jobs:
  js:
    name: JavaScript Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: {version: ^12.0}
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn run bundle-data
      - run: yarn run pretty
      - run: yarn run flow check
      - run: yarn run lint
      - name: Run tests
        run: yarn run test --coverage
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

  bundle-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: { version: ^12.0 }
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn run bundle-data
      - run: yarn run --silent bundle:android

  bundle-ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: { version: ^12.0 }
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn run bundle-data
      - run: yarn run --silent bundle:ios

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with: { version: ^12.0 }
      - uses: actions/setup-ruby@master
        with: { ruby-version: 2.6.3 }
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: bundle check || bundle install --frozen --path vendor/bundle
      - run: android/gradlew androidDependencies --console=plain
      - run: echo 'org.gradle.workers.max=2' >> android/gradle.properties
      - run: bundle exec fastlane android ci-run
