name: Analyze and build the source

on: push

jobs:
  js:
    name: js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: yarn install
    - name: Bundle data, then run flow
      run: |
        yarn run bundle-data
        yarn run flow check
