name: Build and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '17 8 * * *'

permissions:
  contents: read

env:
  MISE_RUBY_COMPILE: 'false'

jobs:
  js:
    name: JavaScript Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - run: pnpm install --frozen-lockfile
      - run: mise run validate-data
      - run: mise run bundle-data
      - run: mise run format:check
      - run: mise run tsc
      - run: mise run lint
      - name: Run tests
        run: mise run test -- --coverage
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0

  ios:
    name: Build for iOS
    runs-on: macos-26
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - run: sudo xcode-select -s /Applications/Xcode_26.4.app
      - run: git fetch --prune --unshallow
      - run: pnpm install --frozen-lockfile
      - run: mise run prebuild
      - run: bundle exec fastlane ios ci-run
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_COMMIT_DESC: $(git log --format=oneline -n 1 $GITHUB_SHA)
          FASTLANE_SKIP_UPDATE_CHECK: '1'
          FASTLANE_DISABLE_ANIMATION: '1'
          SENTRY_ORG: frog-pond-labs
          SENTRY_PROJECT: all-about-olaf
          SENTRY_AUTH_TOKEN: ${{ secrets.HOSTED_SENTRY_AUTH_TOKEN }}
          GITHUB_KEYS_REPOSITORY_TOKEN: ${{ secrets.GITHUB_KEYS_REPOSITORY_TOKEN }}
