name: Build and Deploy

on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: '17 8 * * *'

jobs:
  js:
    name: JavaScript Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - run: npm ci
      - run: mise run validate-data
      - run: mise run bundle-data
      - run: mise run pretty:check
      - run: mise run tsc
      - run: mise run lint
      - name: Run tests
        run: mise run test -- --coverage
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

  ios:
    name: Build for iOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: '3.4.9'
          bundler-cache: true
      - run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - run: git fetch --prune --unshallow
      - run: npm ci
        env:
          SKIP_POSTINSTALL: '1'
      - run: bundle exec pod install --deployment
        working-directory: ./ios
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: bundle exec fastlane ios ci-run
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_COMMIT_DESC: $(git log --format=oneline -n 1 $GITHUB_SHA)
          FASTLANE_SKIP_UPDATE_CHECK: '1'
          FASTLANE_DISABLE_ANIMATION: '1'
          SENTRY_ORG: frog-pond-labs
          SENTRY_PROJECT: all-about-olaf
          SENTRY_AUTH_TOKEN: ${{ secrets.HOSTED_SENTRY_AUTH_TOKEN }}
          GITHUB_KEYS_REPOSITORY_TOKEN: ${{ secrets.GITHUB_KEYS_REPOSITORY_TOKEN }}
