name: Check & Update Cocoapods

on:
  push:
    branches:
      - renovate/**
    paths:
      - package-lock.json

permissions:
  contents: write
  pull-requests: write

jobs:
  ios-podfile-update:
    # Adapted from https://gist.github.com/A-Tokyo/0d811e818513fc4d3272335d2847d748
    name: iOS Update Cocoapods
    runs-on: macos-14
    timeout-minutes: 15
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.COCOAPODS_LOCKFILE_GH_PUSH_TOKEN }}

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: '.node-version'
          cache: npm

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.7'
          bundler-cache: true

      - run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - run: npm ci

      - run: bundle exec -- pod install --verbose
        working-directory: ./ios

      - name: push-on-podfile-change
        run: bash scripts/push-on-podfile-change.sh
        env:
          branch: ${{ github.ref_name }}
          head_ref: ${{ github.ref }}
