name: Check & Update Cocoapods

on:
  push:
    branches:
      - renovate/**
    paths:
      - package-lock.json

permissions:
  contents: write
  pull-requests: write

jobs:
  ios-podfile-update:
    # Adapted from https://gist.github.com/A-Tokyo/0d811e818513fc4d3272335d2847d748
    name: iOS Update Cocoapods
    runs-on: macos-14
    timeout-minutes: 15
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
        with:
          token: ${{ secrets.COCOAPODS_LOCKFILE_GH_PUSH_TOKEN }}

      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: '.node-version'
          cache: npm

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - run: npm ci

      - run: bundle exec -- pod install --verbose
        working-directory: ./ios

      - name: push-on-podfile-change
        run: bash scripts/push-on-podfile-change.sh
        env:
          branch: ${{ github.ref_name }}
          head_ref: ${{ github.ref }}
