name: Check & Update Cocoapods

on:
  pull_request_target:
    branches:
      - dependabot/npm_and_yarn/**

permissions:
  contents: write
  pull-requests: write

jobs:
  ios-podfile-update:
    # Adapted from https://gist.github.com/A-Tokyo/0d811e818513fc4d3272335d2847d748
    name: iOS Update Cocoapods
    runs-on: macos-12
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.COCOAPODS_LOCKFILE_GH_PUSH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '^16.0'
          cache: npm
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - run: npm ci
        env: {SKIP_POSTINSTALL: '1'}
      - run: bundle exec -- pod install --verbose
        working-directory: ./ios
      - name: push-on-podfile-change
        run: bash scripts/push-on-podfile-change.sh
        env:
          branch: ${{ github.ref_name }}
          actor: ${{ github.actor }}
          head_ref: ${{ github.ref }}
