name: Check & Update Cocoapods

on:
  push:
    branches:
      - renovate/**
    paths:
      - package-lock.json

permissions:
  contents: write
  pull-requests: write

jobs:
  ios-podfile-update:
    # Adapted from https://gist.github.com/A-Tokyo/0d811e818513fc4d3272335d2847d748
    name: iOS Update Cocoapods
    runs-on: macos-13
    timeout-minutes: 15
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: ${{ secrets.COCOAPODS_LOCKFILE_GH_PUSH_TOKEN }}

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version-file: '.node-version'
          cache: npm

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - run: sudo xcode-select -s /Applications/Xcode_14.2.app

      - run: npm ci

      - run: bundle exec -- pod install --verbose
        working-directory: ./ios

      - name: push-on-podfile-change
        run: bash scripts/push-on-podfile-change.sh
        env:
          branch: ${{ github.ref_name }}
          head_ref: ${{ github.ref }}
