name: Check & Update Cocoapods

on:
  push:
    branches:
      - renovate/**
    paths:
      - package-lock.json

permissions:
  contents: write
  pull-requests: write

jobs:
  ios-podfile-update:
    # Adapted from https://gist.github.com/A-Tokyo/0d811e818513fc4d3272335d2847d748
    name: iOS Update Cocoapods
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.COCOAPODS_LOCKFILE_GH_PUSH_TOKEN }}

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - run: npm ci

      - run: mise run pods

      - name: push-on-podfile-change
        run: bash scripts/push-on-podfile-change.sh
        env:
          branch: ${{ github.ref_name }}
          head_ref: ${{ github.ref }}
