name: macOS CI Tests

on: [push]

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '^12.0.0'

      - run: yarn install --frozen-lockfile

      - run: yarn run bundle-data
      
      - run: yarn run --silent bundle:ios

  build:
    runs-on: macOS-10.14

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '^12.0.0'

      - run: |
          npm install -g yarn
          yarn --version

      - run: yarn install --frozen-lockfile

      - run: bundle install --frozen --path ./vendor/bundle

      - run: brew tap wix/brew
      - run: brew install applesimutils
      
      - run: mkdir -p ./logs

      - run: bundle exec fastlane ios ci-run
        env:
          GIT_COMMIT_DESC: $(git log --format=oneline -n 1 $GITHUB_SHA)
          FASTLANE_SKIP_UPDATE_CHECK: '1'
          FASTLANE_DISABLE_ANIMATION: '1'
          SENTRY_PROPERTIES: '../ios/sentry.properties'

      - run: yarn detox build e2e --configuration ios.sim.release | xcpretty

      - run: yarn detox test e2e --configuration ios.sim.release --cleanup
