name: Update tsc and eslint files

on:
  issue_comment:
    types:
      - created

jobs:
  tsc-and-lint-updates:
    name: update files
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/makefiles' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '^16.0'
          cache: npm
      - run: make files
      - name: update-tsc-and-lint-files
        run: bash scripts/update-tsc-and-lint-files.sh
        env:
          actor: ${{ github.actor }}
          head_ref: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
